r"""The quasi-Hopf algebra U_q^{(Phi)} sl(2).

This is the algebra U_q^{(Phi)}sl(2) from

    T. Creutzig, A. M. Gainutdinov, I. Runkel, "A quasi-Hopf algebra for
    the triplet vertex operator algebra", arXiv:1712.07260.

It is a modification of the restricted (small) quantum group for sl(2)
at a primitive 2p'th root of unity: same underlying associative
algebra, but with a coproduct that is only coassociative up to
conjugation by a non-trivial associator Phi. This module is a direct
port of the paper authors' own Mathematica implementation
(``hopf-Uqsl2-quasi.txt``, not included in this repository).

As a C-algebra, U_q^{(Phi)}sl(2) is generated by E, F, K^{+-1} with
relations::

    K E K^-1 = q^2 E,   K F K^-1 = q^-2 F,   [E, F] = (K - K^-1) / (q - q^-1)
    E^p = 0 = F^p,      K^{2p} = 1

giving a basis E^a F^b K^c with 0 <= a, b < p and 0 <= c < 2p (so
dimension 2p^3). Writing e0 = (1 + K^p)/2, e1 = (1 - K^p)/2, the
coproduct, counit, antipode, associator and evaluation/coevaluation
elements are::

    Delta(E) = E (x) K + (e0 + q^t e1) (x) E
    Delta(F) = F (x) 1 + (e0 + q^-t e1) K^-1 (x) F
    Delta(K) = K (x) K
    epsilon(E) = epsilon(F) = 0,  epsilon(K) = 1

    S(E) = -(e0 + q^t e1) E K^-1
    S(F) = -(e0 + q^-t e1) K F
    S(K) = K^-1

    Phi = 1 (x) 1 (x) 1 + e1 (x) e1 (x) (K^-t - 1)
    alpha = 1,   beta = e0 + K^-t e1

Here t is an odd integer gauge parameter (t=1 recovers the formula
quoted in the paper's introduction).

Note on the coefficient ring: q genuinely has to be a primitive 2p'th
root of unity here, not a free formal variable -- imposing K^{2p} = 1
together with K E K^-1 = q^2 E forces q^{4p} = 1 by conjugating E
around the cycle 2p times, and separately the commutator [E, F]
involves dividing by q - q^-1, which only has an inverse once q lives
in an actual field. So the coefficient ring is Q(zeta_{2p}) (see
hopfsym.qring.CycloNum), the field generated by a primitive 2p'th root
of unity, exactly mirroring what the original Mathematica code's
``qqreduce``/``qqnzero`` do numerically. Every check in this module
(associativity, coassociativity up to Phi, Delta being an algebra
homomorphism, the antipode axiom, the evaluation/coevaluation
identities) is verified exactly within this field, for every odd t and
p >= 2.

The R-matrix (``r_matrix``), and everything built from it (``monodromy``,
``drinfeld``, the hexagon axioms, and -- via a Gauss-sum identity, see
``ribbon``'s docstring -- ``ribbon`` itself), need one field up,
Q(zeta_{4p}): the R-matrix formula has a q**(t**2/2) term, and t is
always odd, so that is a genuine half-integer power of q. See CLAUDE.md
("A single algebra can need more than one cyclotomic field") for how
CycloNum bridges the two fields. The "F" element (``f_element``) needs
no R-matrix and stays in Q(zeta_{2p}).
"""

from __future__ import annotations

from fractions import Fraction

from ..algebra import QuasiHopfAlgebra
from ..element import Element, TensorKey, tensor
from ..qring import CycloNum
from ..unicode_fmt import TENSOR, superscript

# A basis key is a triple (a, b, c) representing E^a F^b K^c,
# 0 <= a, b < p, 0 <= c < 2p.
BasisKey = tuple


class QuantumSl2Quasi(QuasiHopfAlgebra):
    """U_q^{(Phi)}sl(2) at a primitive 2p'th root of unity, with gauge
    parameter t (must be odd)."""

    def __init__(self, p: int, t: int):
        if p < 2:
            raise ValueError("need p >= 2")
        if t % 2 == 0:
            raise ValueError("t must be odd")
        self.p = p
        self.t = t
        self._comm_ef_cache = {}
        self._mul_basis_cache = {}
        self._comul_basis_cache = {}
        self._antipode_basis_cache = {}
        self._comul_power_cache = {"E": {}, "F": {}, "K": {}}
        self._antipode_power_cache = {"E": {}, "F": {}}
        self._qfact_cache = {}
        self._r_matrix_cache = None
        self._ribbon_cache = None

    def q(self, k: int) -> CycloNum:
        """q**k, as an element of Q(zeta_{2p}) -- q is a primitive 2p'th
        root of unity, see hopfsym.qring for why q cannot just be a free
        formal variable here."""
        return CycloNum.power(2 * self.p, k)

    def q_half(self, two_k: int) -> CycloNum:
        """q**(two_k/2), as an element of Q(zeta_{4p}).

        The R-matrix (see r_matrix()) needs q**(t**2/2), a genuine
        half-integer power of q since the gauge parameter t is always odd
        -- so it (and everything built from it: the hexagon axiom,
        monodromy, ribbon and Drinfeld elements) lives one field up from
        the rest of the algebra, in Q(zeta_{4p}) rather than Q(zeta_{2p}).
        Writing zeta_{4p} for q**(1/2) (principal branch, matching the
        original Mathematica code's ``qq -> N[Exp[Pi I/pp], ...]``
        numerical convention), q**(two_k/2) = zeta_{4p}**two_k for any
        integer two_k -- callers pass the *doubled* exponent so this is
        always an exact integer power.
        """
        return CycloNum.power(4 * self.p, two_k)

    def _qnum(self, a: int) -> CycloNum:
        """[a} = (q**a - q**-a) / (q - q**-1), a in Q(zeta_{2p})."""
        return (self.q(a) - self.q(-a)) / (self.q(1) - self.q(-1))

    def _qfact(self, a: int) -> CycloNum:
        """[a]! = [a} [a-1} ... [1}, memoised (only depends on a)."""
        cached = self._qfact_cache.get(a)
        if cached is not None:
            return cached
        result = CycloNum.one(2 * self.p) if a == 0 else self._qfact(a - 1) * self._qnum(a)
        self._qfact_cache[a] = result
        return result

    # -- basic data -----------------------------------------------------
    def basis(self):
        p = self.p
        return [(a, b, c) for a in range(p) for b in range(p) for c in range(2 * p)]

    def unit(self) -> Element:
        return Element.basis((0, 0, 0))

    def _idempotents(self):
        """e0 = (1 + K^p)/2,  e1 = (1 - K^p)/2."""
        one = self.unit()
        Kp = Element.basis((0, 0, self.p))
        e0 = Fraction(1, 2) * (one + Kp)
        e1 = Fraction(1, 2) * (one - Kp)
        return e0, e1

    # -- product ----------------------------------------------------------
    def multiply_basis(self, b1: BasisKey, b2: BasisKey) -> Element:
        # Memoised: the same pair of basis elements gets multiplied many
        # times over during a typical axiom check.
        key = (b1, b2)
        cached = self._mul_basis_cache.get(key)
        if cached is not None:
            return cached
        a1, f1, k1 = b1
        a2, f2, k2 = b2
        tokens = [("E", a1), ("F", f1), ("K", k1), ("E", a2), ("F", f2), ("K", k2)]
        result = self._reduce_word(tokens)
        self._mul_basis_cache[key] = result
        return result

    def _reduce_word(self, tokens) -> Element:
        """Reduce a list of (letter, exponent) tokens, letters in
        {"E", "F", "K"}, to an Element in the normal-form basis
        E^a F^b K^c. This is *the* place the defining relations of the
        algebra live; everything else (coproduct, antipode, ...) only
        ever calls ``self.mul``, which bottoms out here.
        """
        p = self.p
        tokens = [t for t in tokens if t[1] != 0]

        # E^p = 0 = F^p.
        for letter, exp in tokens:
            if letter in ("E", "F") and exp >= p:
                return Element.zero()

        for i in range(len(tokens) - 1):
            (l1, e1), (l2, e2) = tokens[i], tokens[i + 1]

            if l1 == l2:
                new_tokens = tokens[:i] + [(l1, e1 + e2)] + tokens[i + 2:]
                return self._reduce_word(new_tokens)

            if l1 == "K" and l2 == "E":
                # K^m E^n = q^{2mn} E^n K^m
                coeff = self.q(2 * e1 * e2)
                new_tokens = tokens[:i] + [("E", e2), ("K", e1)] + tokens[i + 2:]
                return coeff * self._reduce_word(new_tokens)

            if l1 == "K" and l2 == "F":
                # K^m F^n = q^{-2mn} F^n K^m
                coeff = self.q(-2 * e1 * e2)
                new_tokens = tokens[:i] + [("F", e2), ("K", e1)] + tokens[i + 2:]
                return coeff * self._reduce_word(new_tokens)

            if l1 == "F" and l2 == "E":
                # F^m E^n = E^n F^m - [E^n, F^m]
                swapped = tokens[:i] + [("E", e2), ("F", e1)] + tokens[i + 2:]
                commutator = self._comm_ef(e2, e1)  # [E^n, F^m]
                correction = self._sandwich(tokens[:i], commutator, tokens[i + 2:])
                return self._reduce_word(swapped) - correction

        # No more inversions or merges left: word is E^a F^b K^c already.
        a = sum(exp for letter, exp in tokens if letter == "E")
        b = sum(exp for letter, exp in tokens if letter == "F")
        c = sum(exp for letter, exp in tokens if letter == "K") % (2 * p)
        if a >= p or b >= p:
            return Element.zero()
        return Element.basis((a, b, c))

    def _sandwich(self, prefix_tokens, middle: Element, suffix_tokens) -> Element:
        """prefix * middle * suffix, where prefix/suffix are token lists
        and middle is an already-computed Element."""
        left = self._reduce_word(prefix_tokens) if prefix_tokens else self.unit()
        right = self._reduce_word(suffix_tokens) if suffix_tokens else self.unit()
        return self.mul(self.mul(left, middle), right)

    def _comm_ef(self, m: int, n: int) -> Element:
        """[E^m, F^n], computed by the same recursion as the defining
        relation [E, F] = (K - K^-1) / (q - q^-1):

            [E, F^n]   = F [E, F^{n-1}] + [E, F] F^{n-1}      (n > 1)
            [E^m, F^n] = E [E^{m-1}, F^n] + [E, F^n] E^{m-1}  (m > 1)

        Memoised per algebra instance since it only depends on (m, n).
        """
        key = (m, n)
        if key in self._comm_ef_cache:
            return self._comm_ef_cache[key]

        if m == 1 and n == 1:
            p = self.p
            K = Element.basis((0, 0, 1))
            Kinv = Element.basis((0, 0, 2 * p - 1))
            q = self.q(1)
            qinv = self.q(-1)
            result = (K - Kinv) * (1 / (q - qinv))
        elif m == 1:  # n > 1
            F1 = Element.basis((0, 1, 0))
            Fnm1 = Element.basis((0, n - 1, 0))
            result = self.mul(F1, self._comm_ef(1, n - 1)) + self.mul(self._comm_ef(1, 1), Fnm1)
        else:  # m > 1
            E1 = Element.basis((1, 0, 0))
            Emm1 = Element.basis((m - 1, 0, 0))
            result = self.mul(E1, self._comm_ef(m - 1, n)) + self.mul(self._comm_ef(1, n), Emm1)

        self._comm_ef_cache[key] = result
        return result

    # -- coproduct --------------------------------------------------------
    def _comul_E1(self) -> Element:
        e0, e1 = self._idempotents()
        combo = e0 + self.q(self.t) * e1
        return tensor(Element.basis((1, 0, 0)), Element.basis((0, 0, 1))) + tensor(
            combo, Element.basis((1, 0, 0))
        )

    def _comul_F1(self) -> Element:
        e0, e1 = self._idempotents()
        combo = e0 + self.q(-self.t) * e1
        left = self.mul(combo, Element.basis((0, 0, 2 * self.p - 1)))
        return tensor(Element.basis((0, 1, 0)), self.unit()) + tensor(
            left, Element.basis((0, 1, 0))
        )

    def _comul_K1(self) -> Element:
        K1 = Element.basis((0, 0, 1))
        return tensor(K1, K1)

    def comul(self, elem: Element) -> Element:
        result = Element()
        for (a, b, c), coeff in elem.terms.items():
            result = result + coeff * self._comul_basis(a, b, c)
        return result

    def _comul_generator_power(self, letter: str, k: int) -> Element:
        """Delta(g)^k for g in {E, F, K}, built up *incrementally* and
        cached: computing Delta(E)^a for every a = 0, ..., p-1 this way
        costs one tensor_mul per step (O(p) total across every basis
        element sharing that E-power), instead of redoing an O(a)
        multiplication chain from scratch for every single basis
        element -- which is what made comul() the dominant cost for
        p >= 4 before this cache existed.
        """
        cache = self._comul_power_cache[letter]
        if k in cache:
            return cache[k]
        if k == 0:
            result = tensor(self.unit(), self.unit())
        else:
            from ..element import tensor_mul  # local import to avoid a cycle at module load

            generator1 = {"E": self._comul_E1, "F": self._comul_F1, "K": self._comul_K1}[letter]()
            result = tensor_mul(self, self._comul_generator_power(letter, k - 1), generator1)
        cache[k] = result
        return result

    def _comul_basis(self, a: int, b: int, c: int) -> Element:
        """Delta(E^a F^b K^c) = Delta(E)^a * Delta(F)^b * Delta(K)^c,
        the power taken with the H (x) H product (Delta is an algebra
        homomorphism, so this is forced)."""
        key = (a, b, c)
        cached = self._comul_basis_cache.get(key)
        if cached is not None:
            return cached

        from ..element import tensor_mul  # local import to avoid a cycle at module load

        eE = self._comul_generator_power("E", a)
        eF = self._comul_generator_power("F", b)
        eK = self._comul_generator_power("K", c)
        result = tensor_mul(self, tensor_mul(self, eE, eF), eK)
        self._comul_basis_cache[key] = result
        return result

    # -- counit -------------------------------------------------------------
    def counit(self, elem: Element):
        total = CycloNum.zero(2 * self.p)
        for (a, b, c), coeff in elem.terms.items():
            if a == 0 and b == 0:
                total = total + coeff
        return total

    # -- antipode -------------------------------------------------------------
    def _antipode_E1(self) -> Element:
        e0, e1 = self._idempotents()
        combo = e0 + self.q(self.t) * e1
        EKinv = Element.basis((1, 0, 2 * self.p - 1))
        return -self.mul(combo, EKinv)

    def _antipode_F1(self) -> Element:
        e0, e1 = self._idempotents()
        combo = e0 + self.q(-self.t) * e1
        K = Element.basis((0, 0, 1))
        F = Element.basis((0, 1, 0))
        return -self.mul(self.mul(combo, K), F)

    def _antipode_power(self, letter: str, m: int) -> Element:
        """S(g^m) = S(g) * S(g^{m-1}) = S(g)^m (S is an anti-homomorphism
        and g^m is a product of a single generator with itself). Cached
        incrementally per letter, for the same reason as
        _comul_generator_power above."""
        cache = self._antipode_power_cache[letter]
        if m in cache:
            return cache[m]
        if m == 0:
            result = self.unit()
        else:
            generator1 = self._antipode_E1() if letter == "E" else self._antipode_F1()
            result = self.mul(generator1, self._antipode_power(letter, m - 1))
        cache[m] = result
        return result

    def antipode(self, elem: Element) -> Element:
        result = Element()
        for (a, b, c), coeff in elem.terms.items():
            result = result + coeff * self._antipode_basis(a, b, c)
        return result

    def _antipode_basis(self, a: int, b: int, c: int) -> Element:
        """S(E^a F^b K^c) = S(K^c) S(F^b) S(E^a) (S reverses order)."""
        key = (a, b, c)
        cached = self._antipode_basis_cache.get(key)
        if cached is not None:
            return cached
        sK = Element.basis((0, 0, (-c) % (2 * self.p)))
        sF = self._antipode_power("F", b)
        sE = self._antipode_power("E", a)
        result = self.mul(self.mul(sK, sF), sE)
        self._antipode_basis_cache[key] = result
        return result

    # -- associator and evaluation/coevaluation elements ------------------------
    def associator(self) -> Element:
        e0, e1 = self._idempotents()
        one = self.unit()
        term1 = tensor(tensor(one, one), one)
        Kmt_minus_one = Element.basis((0, 0, (-self.t) % (2 * self.p))) - one
        term2 = tensor(tensor(e1, e1), Kmt_minus_one)
        return term1 + term2

    def associator_inv(self) -> Element:
        e0, e1 = self._idempotents()
        one = self.unit()
        term1 = tensor(tensor(one, one), one)
        Kt_minus_one = Element.basis((0, 0, self.t % (2 * self.p))) - one
        term2 = tensor(tensor(e1, e1), Kt_minus_one)
        return term1 + term2

    def alpha(self) -> Element:
        return self.unit()

    def beta(self) -> Element:
        # beta = e0 + K^{-t} e1  (note: -t, the gauge parameter, not -1)
        e0, e1 = self._idempotents()
        Kmt = Element.basis((0, 0, (-self.t) % (2 * self.p)))
        return e0 + self.mul(Kmt, e1)

    # -- R-matrix -----------------------------------------------------------
    def r_matrix(self) -> Element:
        r"""The universal R-matrix, an element of H (x) H, in Q(zeta_{4p})
        (see q_half() for why):

            R = 1/(4p) sum_{n=0}^{p-1} sum_{s,r=0}^{2p-1}
                (q-q^-1)^n/[n]! * q^{n(n-1)/2 - 2sr} *
                (1 + q^{tr} + q^{-t(n+s)} + q^{t^2/2 + tr - t(n+s)}) *
                K^s E^n (x) K^r F^n

        Ported from ``RR`` in the original Mathematica implementation
        (also eq:R-quasiH in the paper); K^s E^n and K^r F^n are put in normal
        form (E^n K^s and F^n K^r, picking up q^{2sn} / q^{-2rn}
        respectively) via the same K-past-E/F relation used everywhere
        else in this module.
        """
        if self._r_matrix_cache is not None:
            return self._r_matrix_cache

        p, t = self.p, self.t
        result = Element()
        for n in range(p):
            qdiff_n = (self.q(1) - self.q(-1)) ** n
            coeff_n = (qdiff_n / self._qfact(n)).embed(4 * p)
            for s in range(2 * p):
                for r in range(2 * p):
                    qA2 = n * (n - 1) - 4 * s * r  # doubled exponent of q^{n(n-1)/2 - 2sr}
                    bracket_exps2 = (
                        0,
                        2 * t * r,
                        -2 * t * (n + s),
                        t * t + 2 * t * r - 2 * t * (n + s),
                    )
                    bracket = sum((self.q_half(qA2 + e2) for e2 in bracket_exps2), CycloNum.zero(4 * p))
                    reorder_coeff = self.q_half(4 * s * n - 4 * r * n)  # q^{2sn - 2rn}
                    left_key = (n, 0, s % (2 * p))
                    right_key = (0, n, r % (2 * p))
                    total = coeff_n * bracket * reorder_coeff * Fraction(1, 4 * p)
                    result.add_term(TensorKey((left_key, right_key)), total)

        self._r_matrix_cache = result
        return result

    # monodromy()/drinfeld() are generic (see QuasiHopfAlgebra) -- not
    # overridden here.

    def ribbon(self) -> Element:
        r"""The ribbon element, an element of H:

            v = (1-i)/(2 sqrt(p)) * sum_{n=0}^{p-1} sum_{j in Z_2p}
                (q-q^-1)^n/[n]! * q^{n(j-1/2) + 1/2(j+p+1)^2} * F^n E^n K^j

        Ported from ``rib`` in the original Mathematica implementation
        (also eq:ribbon-quasiH in the paper).

        The prefactor (1-i)/(2 sqrt(p)) is an *exact* algebraic number,
        not a numerical approximation -- it is expressed here via the
        classical quadratic Gauss sum identity

            sum_{a=0}^{2p-1} q^{-a^2/2} == (1-i) sqrt(p)

        (eq:gauss-sum in the paper; verified numerically for a range of p
        before relying on it here, see test_ribbon.py), which lets the
        whole prefactor be written as G/(2p) with
        G = sum_{a=0}^{2p-1} q^{-a^2/2} -- an honest finite sum of
        integer powers of q**(1/2), i.e. a genuine element of
        Q(zeta_{4p}), computed exactly the same way as everything else in
        this module (no black-box sqrt() or complex arithmetic anywhere).
        """
        if self._ribbon_cache is not None:
            return self._ribbon_cache

        p = self.p
        N = 4 * p
        gauss_sum = sum((self.q_half(-a * a) for a in range(2 * p)), CycloNum.zero(N))
        prefactor = gauss_sum * Fraction(1, 2 * p)

        result = Element()
        for n in range(p):
            coeff_n = ((self.q(1) - self.q(-1)) ** n / self._qfact(n)).embed(N)
            for j in range(2 * p):
                doubled_exp = 2 * n * j - n + (j + p + 1) ** 2
                scalar = prefactor * self.q_half(doubled_exp) * coeff_n
                basis_elem = self._reduce_word([("F", n), ("E", n), ("K", j)])
                for k, c in basis_elem.terms.items():
                    result.add_term(k, scalar * c)

        self._ribbon_cache = result
        return result

    # f_element() is generic (see QuasiHopfAlgebra) -- not overridden here.

    # -- readable output ---------------------------------------------------
    def pretty(self, elem: Element) -> str:
        """A human-readable string for an Element in this algebra's basis,
        e.g. ``"2*E² F K³ + (1+q)*K""`` instead of ``Element``'s generic
        ``repr`` (which only knows basis keys as opaque tuples -- see
        element.py's module docstring). Coefficients that are CycloNum
        values are shown as polynomials in ``q`` (the field's generator is
        q itself for the Q(zeta_{2p}) structure maps, or q**(1/2) for the
        Q(zeta_{4p}) ones used by r_matrix/monodromy/drinfeld/ribbon --
        see this module's docstring for why there are two fields).
        """
        if not elem.terms:
            return "0"
        rendered = []
        for key, coeff in sorted(elem.terms.items(), key=lambda kv: kv[0]):
            coeff_str = self._format_coeff(coeff)
            if coeff_str == "0":
                continue
            key_str = self._format_key(key)
            if key_str == "1":
                rendered.append(coeff_str)
            elif coeff_str == "1":
                rendered.append(key_str)
            elif coeff_str == "-1":
                rendered.append(f"-{key_str}")
            elif " + " in coeff_str or " - " in coeff_str:
                rendered.append(f"({coeff_str})*{key_str}")
            else:
                rendered.append(f"{coeff_str}*{key_str}")
        if not rendered:
            return "0"
        out = rendered[0]
        for term in rendered[1:]:
            out += f" - {term[1:]}" if term.startswith("-") else f" + {term}"
        return out

    def _format_key(self, key) -> str:
        if isinstance(key, TensorKey):
            return f" {TENSOR} ".join(self._format_key(k) for k in key)
        a, b, c = key
        factors = [
            f"{letter}{superscript(exp)}" if exp > 1 else letter
            for letter, exp in (("E", a), ("F", b), ("K", c))
            if exp != 0
        ]
        return " ".join(factors) if factors else "1"

    def _format_coeff(self, c) -> str:
        if isinstance(c, CycloNum):
            return self._format_cyclonum(c)
        if isinstance(c, Fraction):
            return str(c.numerator) if c.denominator == 1 else f"{c.numerator}/{c.denominator}"
        return str(c)

    def _format_cyclonum(self, c: CycloNum) -> str:
        if c.n is None:
            return str(c.poly.coeffs[0])
        if c.n == 2 * self.p:
            power = lambda k: "" if k == 0 else ("q" if k == 1 else f"q{superscript(k)}")
        elif c.n == 4 * self.p:
            # x = zeta_{4p} = q**(1/2): even k is an integer power of q,
            # odd k a genuine half-integer one.
            def power(k):
                if k == 0:
                    return ""
                if k % 2 == 0:
                    return "q" if k == 2 else f"q{superscript(k // 2)}"
                return f"q{superscript('(1/2)')}" if k == 1 else f"q{superscript(f'({k}/2)')}"
        else:  # pragma: no cover - fallback for an unanticipated field
            symbol = f"zeta_{c.n}"
            power = lambda k: "" if k == 0 else (symbol if k == 1 else f"{symbol}{superscript(k)}")

        terms = []
        for k, coeff in enumerate(c.poly.coeffs):
            if coeff == 0:
                continue
            p_str = power(k)
            if p_str == "":
                terms.append(f"{coeff}")
            elif coeff == 1:
                terms.append(p_str)
            elif coeff == -1:
                terms.append(f"-{p_str}")
            else:
                terms.append(f"{coeff}*{p_str}")
        if not terms:
            return "0"
        out = terms[0]
        for t in terms[1:]:
            out += f" - {t[1:]}" if t.startswith("-") else f" + {t}"
        return out
