r"""The quasi-Hopf algebra U_q^{(Phi)} sl(2).

This is the algebra U_q^{(Phi)}sl(2) from

    T. Creutzig, A. M. Gainutdinov, I. Runkel, "A quasi-Hopf algebra for
    the triplet vertex operator algebra", arXiv:1712.07260.

It is a modification of the restricted (small) quantum group for sl(2)
at a primitive 2p'th root of unity: same underlying associative
algebra, but with a coproduct that is only coassociative up to
conjugation by a non-trivial associator Phi. This module is a direct
port of the original Mathematica implementation, see
``reference/hopf-Uqsl2-quasi.txt``.

As a C-algebra, U_q^{(Phi)}sl(2) is generated by E, F, K^{+-1} with
relations::

    K E K^-1 = q^2 E,   K F K^-1 = q^-2 F,   [E, F] = (K - K^-1) / (q - q^-1)
    E^p = 0 = F^p,      K^{2p} = 1

giving a basis E^a F^b K^c with 0 <= a, b < p and 0 <= c < 2p (so
dimension 2p^3). Writing e0 = (1 + K^p)/2, e1 = (1 - K^p)/2, the
coproduct, counit, antipode, associator and evaluation/coevaluation
elements are::

    Delta(E) = E (x) K + (e0 + q^t e1) (x) E
    Delta(F) = F (x) 1 + (e0 + q^-t e1) K^-1 (x) F
    Delta(K) = K (x) K
    epsilon(E) = epsilon(F) = 0,  epsilon(K) = 1

    S(E) = -(e0 + q^t e1) E K^-1
    S(F) = -(e0 + q^-t e1) K F
    S(K) = K^-1

    Phi = 1 (x) 1 (x) 1 + e1 (x) e1 (x) (K^-t - 1)
    alpha = 1,   beta = e0 + K^-t e1

Here t is an odd integer gauge parameter (t=1 recovers the formula
quoted in the paper's introduction).

Note on the coefficient ring: q genuinely has to be a primitive 2p'th
root of unity here, not a free formal variable -- imposing K^{2p} = 1
together with K E K^-1 = q^2 E forces q^{4p} = 1 by conjugating E
around the cycle 2p times, and separately the commutator [E, F]
involves dividing by q - q^-1, which only has an inverse once q lives
in an actual field. So the coefficient ring is Q(zeta_{2p}) (see
hopfsym.qring.CycloNum), the field generated by a primitive 2p'th root
of unity, exactly mirroring what the original Mathematica code's
``qqreduce``/``qqnzero`` do numerically. Every check in this module
(associativity, coassociativity up to Phi, Delta being an algebra
homomorphism, the antipode axiom) is verified exactly within this
field, for every odd t and p >= 2. The R-matrix, ribbon element and
hexagon axioms are not yet ported; see CLAUDE.md for the plan.
"""

from __future__ import annotations

from fractions import Fraction

from ..algebra import QuasiHopfAlgebra
from ..element import Element, tensor
from ..qring import CycloNum

# A basis key is a triple (a, b, c) representing E^a F^b K^c,
# 0 <= a, b < p, 0 <= c < 2p.
BasisKey = tuple


class QuantumSl2Quasi(QuasiHopfAlgebra):
    """U_q^{(Phi)}sl(2) at a primitive 2p'th root of unity, with gauge
    parameter t (must be odd)."""

    def __init__(self, p: int, t: int):
        if p < 2:
            raise ValueError("need p >= 2")
        if t % 2 == 0:
            raise ValueError("t must be odd")
        self.p = p
        self.t = t
        self._comm_ef_cache = {}
        self._mul_basis_cache = {}
        self._comul_basis_cache = {}
        self._antipode_basis_cache = {}
        self._comul_power_cache = {"E": {}, "F": {}, "K": {}}
        self._antipode_power_cache = {"E": {}, "F": {}}

    def q(self, k: int) -> CycloNum:
        """q**k, as an element of Q(zeta_{2p}) -- q is a primitive 2p'th
        root of unity, see hopfsym.qring for why q cannot just be a free
        formal variable here."""
        return CycloNum.power(2 * self.p, k)

    # -- basic data -----------------------------------------------------
    def basis(self):
        p = self.p
        return [(a, b, c) for a in range(p) for b in range(p) for c in range(2 * p)]

    def unit(self) -> Element:
        return Element.basis((0, 0, 0))

    def _idempotents(self):
        """e0 = (1 + K^p)/2,  e1 = (1 - K^p)/2."""
        one = self.unit()
        Kp = Element.basis((0, 0, self.p))
        e0 = Fraction(1, 2) * (one + Kp)
        e1 = Fraction(1, 2) * (one - Kp)
        return e0, e1

    # -- product ----------------------------------------------------------
    def multiply_basis(self, b1: BasisKey, b2: BasisKey) -> Element:
        # Memoised: the same pair of basis elements gets multiplied many
        # times over during a typical axiom check.
        key = (b1, b2)
        cached = self._mul_basis_cache.get(key)
        if cached is not None:
            return cached
        a1, f1, k1 = b1
        a2, f2, k2 = b2
        tokens = [("E", a1), ("F", f1), ("K", k1), ("E", a2), ("F", f2), ("K", k2)]
        result = self._reduce_word(tokens)
        self._mul_basis_cache[key] = result
        return result

    def _reduce_word(self, tokens) -> Element:
        """Reduce a list of (letter, exponent) tokens, letters in
        {"E", "F", "K"}, to an Element in the normal-form basis
        E^a F^b K^c. This is *the* place the defining relations of the
        algebra live; everything else (coproduct, antipode, ...) only
        ever calls ``self.mul``, which bottoms out here.
        """
        p = self.p
        tokens = [t for t in tokens if t[1] != 0]

        # E^p = 0 = F^p.
        for letter, exp in tokens:
            if letter in ("E", "F") and exp >= p:
                return Element.zero()

        for i in range(len(tokens) - 1):
            (l1, e1), (l2, e2) = tokens[i], tokens[i + 1]

            if l1 == l2:
                new_tokens = tokens[:i] + [(l1, e1 + e2)] + tokens[i + 2:]
                return self._reduce_word(new_tokens)

            if l1 == "K" and l2 == "E":
                # K^m E^n = q^{2mn} E^n K^m
                coeff = self.q(2 * e1 * e2)
                new_tokens = tokens[:i] + [("E", e2), ("K", e1)] + tokens[i + 2:]
                return coeff * self._reduce_word(new_tokens)

            if l1 == "K" and l2 == "F":
                # K^m F^n = q^{-2mn} F^n K^m
                coeff = self.q(-2 * e1 * e2)
                new_tokens = tokens[:i] + [("F", e2), ("K", e1)] + tokens[i + 2:]
                return coeff * self._reduce_word(new_tokens)

            if l1 == "F" and l2 == "E":
                # F^m E^n = E^n F^m - [E^n, F^m]
                swapped = tokens[:i] + [("E", e2), ("F", e1)] + tokens[i + 2:]
                commutator = self._comm_ef(e2, e1)  # [E^n, F^m]
                correction = self._sandwich(tokens[:i], commutator, tokens[i + 2:])
                return self._reduce_word(swapped) - correction

        # No more inversions or merges left: word is E^a F^b K^c already.
        a = sum(exp for letter, exp in tokens if letter == "E")
        b = sum(exp for letter, exp in tokens if letter == "F")
        c = sum(exp for letter, exp in tokens if letter == "K") % (2 * p)
        if a >= p or b >= p:
            return Element.zero()
        return Element.basis((a, b, c))

    def _sandwich(self, prefix_tokens, middle: Element, suffix_tokens) -> Element:
        """prefix * middle * suffix, where prefix/suffix are token lists
        and middle is an already-computed Element."""
        left = self._reduce_word(prefix_tokens) if prefix_tokens else self.unit()
        right = self._reduce_word(suffix_tokens) if suffix_tokens else self.unit()
        return self.mul(self.mul(left, middle), right)

    def _comm_ef(self, m: int, n: int) -> Element:
        """[E^m, F^n], computed by the same recursion as the defining
        relation [E, F] = (K - K^-1) / (q - q^-1):

            [E, F^n]   = F [E, F^{n-1}] + [E, F] F^{n-1}      (n > 1)
            [E^m, F^n] = E [E^{m-1}, F^n] + [E, F^n] E^{m-1}  (m > 1)

        Memoised per algebra instance since it only depends on (m, n).
        """
        key = (m, n)
        if key in self._comm_ef_cache:
            return self._comm_ef_cache[key]

        if m == 1 and n == 1:
            p = self.p
            K = Element.basis((0, 0, 1))
            Kinv = Element.basis((0, 0, 2 * p - 1))
            q = self.q(1)
            qinv = self.q(-1)
            result = (K - Kinv) * (1 / (q - qinv))
        elif m == 1:  # n > 1
            F1 = Element.basis((0, 1, 0))
            Fnm1 = Element.basis((0, n - 1, 0))
            result = self.mul(F1, self._comm_ef(1, n - 1)) + self.mul(self._comm_ef(1, 1), Fnm1)
        else:  # m > 1
            E1 = Element.basis((1, 0, 0))
            Emm1 = Element.basis((m - 1, 0, 0))
            result = self.mul(E1, self._comm_ef(m - 1, n)) + self.mul(self._comm_ef(1, n), Emm1)

        self._comm_ef_cache[key] = result
        return result

    # -- coproduct --------------------------------------------------------
    def _comul_E1(self) -> Element:
        e0, e1 = self._idempotents()
        combo = e0 + self.q(self.t) * e1
        return tensor(Element.basis((1, 0, 0)), Element.basis((0, 0, 1))) + tensor(
            combo, Element.basis((1, 0, 0))
        )

    def _comul_F1(self) -> Element:
        e0, e1 = self._idempotents()
        combo = e0 + self.q(-self.t) * e1
        left = self.mul(combo, Element.basis((0, 0, 2 * self.p - 1)))
        return tensor(Element.basis((0, 1, 0)), self.unit()) + tensor(
            left, Element.basis((0, 1, 0))
        )

    def _comul_K1(self) -> Element:
        K1 = Element.basis((0, 0, 1))
        return tensor(K1, K1)

    def comul(self, elem: Element) -> Element:
        result = Element()
        for (a, b, c), coeff in elem.terms.items():
            result = result + coeff * self._comul_basis(a, b, c)
        return result

    def _comul_generator_power(self, letter: str, k: int) -> Element:
        """Delta(g)^k for g in {E, F, K}, built up *incrementally* and
        cached: computing Delta(E)^a for every a = 0, ..., p-1 this way
        costs one tensor_mul per step (O(p) total across every basis
        element sharing that E-power), instead of redoing an O(a)
        multiplication chain from scratch for every single basis
        element -- which is what made comul() the dominant cost for
        p >= 4 before this cache existed.
        """
        cache = self._comul_power_cache[letter]
        if k in cache:
            return cache[k]
        if k == 0:
            result = tensor(self.unit(), self.unit())
        else:
            from ..element import tensor_mul  # local import to avoid a cycle at module load

            generator1 = {"E": self._comul_E1, "F": self._comul_F1, "K": self._comul_K1}[letter]()
            result = tensor_mul(self, self._comul_generator_power(letter, k - 1), generator1)
        cache[k] = result
        return result

    def _comul_basis(self, a: int, b: int, c: int) -> Element:
        """Delta(E^a F^b K^c) = Delta(E)^a * Delta(F)^b * Delta(K)^c,
        the power taken with the H (x) H product (Delta is an algebra
        homomorphism, so this is forced)."""
        key = (a, b, c)
        cached = self._comul_basis_cache.get(key)
        if cached is not None:
            return cached

        from ..element import tensor_mul  # local import to avoid a cycle at module load

        eE = self._comul_generator_power("E", a)
        eF = self._comul_generator_power("F", b)
        eK = self._comul_generator_power("K", c)
        result = tensor_mul(self, tensor_mul(self, eE, eF), eK)
        self._comul_basis_cache[key] = result
        return result

    # -- counit -------------------------------------------------------------
    def counit(self, elem: Element):
        total = CycloNum.zero(2 * self.p)
        for (a, b, c), coeff in elem.terms.items():
            if a == 0 and b == 0:
                total = total + coeff
        return total

    # -- antipode -------------------------------------------------------------
    def _antipode_E1(self) -> Element:
        e0, e1 = self._idempotents()
        combo = e0 + self.q(self.t) * e1
        EKinv = Element.basis((1, 0, 2 * self.p - 1))
        return -self.mul(combo, EKinv)

    def _antipode_F1(self) -> Element:
        e0, e1 = self._idempotents()
        combo = e0 + self.q(-self.t) * e1
        K = Element.basis((0, 0, 1))
        F = Element.basis((0, 1, 0))
        return -self.mul(self.mul(combo, K), F)

    def _antipode_power(self, letter: str, m: int) -> Element:
        """S(g^m) = S(g) * S(g^{m-1}) = S(g)^m (S is an anti-homomorphism
        and g^m is a product of a single generator with itself). Cached
        incrementally per letter, for the same reason as
        _comul_generator_power above."""
        cache = self._antipode_power_cache[letter]
        if m in cache:
            return cache[m]
        if m == 0:
            result = self.unit()
        else:
            generator1 = self._antipode_E1() if letter == "E" else self._antipode_F1()
            result = self.mul(generator1, self._antipode_power(letter, m - 1))
        cache[m] = result
        return result

    def antipode(self, elem: Element) -> Element:
        result = Element()
        for (a, b, c), coeff in elem.terms.items():
            result = result + coeff * self._antipode_basis(a, b, c)
        return result

    def _antipode_basis(self, a: int, b: int, c: int) -> Element:
        """S(E^a F^b K^c) = S(K^c) S(F^b) S(E^a) (S reverses order)."""
        key = (a, b, c)
        cached = self._antipode_basis_cache.get(key)
        if cached is not None:
            return cached
        sK = Element.basis((0, 0, (-c) % (2 * self.p)))
        sF = self._antipode_power("F", b)
        sE = self._antipode_power("E", a)
        result = self.mul(self.mul(sK, sF), sE)
        self._antipode_basis_cache[key] = result
        return result

    # -- associator and evaluation/coevaluation elements ------------------------
    def associator(self) -> Element:
        e0, e1 = self._idempotents()
        one = self.unit()
        term1 = tensor(tensor(one, one), one)
        Kmt_minus_one = Element.basis((0, 0, (-self.t) % (2 * self.p))) - one
        term2 = tensor(tensor(e1, e1), Kmt_minus_one)
        return term1 + term2

    def associator_inv(self) -> Element:
        e0, e1 = self._idempotents()
        one = self.unit()
        term1 = tensor(tensor(one, one), one)
        Kt_minus_one = Element.basis((0, 0, self.t % (2 * self.p))) - one
        term2 = tensor(tensor(e1, e1), Kt_minus_one)
        return term1 + term2

    def alpha(self) -> Element:
        return self.unit()

    def beta(self) -> Element:
        # beta = e0 + K^{-t} e1  (note: -t, the gauge parameter, not -1)
        e0, e1 = self._idempotents()
        Kmt = Element.basis((0, 0, (-self.t) % (2 * self.p)))
        return e0 + self.mul(Kmt, e1)
