r"""The restricted quantum group U_res sl(2), with K^p = 1 (not K^{2p} = 1).

This is *not* a direct Mathematica port (there is no reference file for
it) -- it is the honest Hopf algebra of arXiv:1712.07260, Section 4.1
(``\UresSL2``, generators E, F, K^{+-1}, relations \eqref{Uq-relations}
and \eqref{EpFpK2p-rel}, coproduct/counit/antipode \eqref{eq:coprod}),
*except* that K is taken to have order p rather than 2p, per Ingo's
request. As a C-algebra::

    K E K^-1 = q^2 E,   K F K^-1 = q^-2 F,   [E, F] = (K - K^-1) / (q - q^-1)
    E^p = 0 = F^p,      K^p = 1

giving a basis E^a F^b K^c with 0 <= a, b, c < p (dimension p^3, half of
``QuantumSl2Quasi``'s 2p^3). The coproduct, counit and antipode are the
plain, untwisted ones (no gauge parameter t, no central idempotents)::

    Delta(E) = E (x) K + 1 (x) E,   Delta(F) = F (x) 1 + K^-1 (x) F,   Delta(K) = K (x) K
    epsilon(E) = epsilon(F) = 0,  epsilon(K) = 1
    S(E) = -E K^-1,   S(F) = -K F,   S(K) = K^-1

This is an honest Hopf algebra: the associator is trivial and
alpha = beta = 1.

Why K^p = 1 is a legitimate variant, not just a typo for K^{2p} = 1:
in ``QuantumSl2Quasi`` (K^{2p} = 1), the element K^p is already central
of order (dividing) 2 -- conjugating K^p past E gives
q^{2p} E = E automatically, since q^{2p} = 1 is exactly what "q a 2p'th
root of unity" means. That central K^p is precisely e0 - e1 (see
``QuantumSl2Quasi._idempotents``). Since K is grouplike
(Delta(K) = K (x) K), the ideal generated by (K^p - 1) is automatically
a Hopf ideal (a standard fact for any central grouplike element), so
quotienting by K^p = 1 -- i.e. setting e1 = 0, e0 = 1 -- is guaranteed
to again be a well-defined Hopf algebra, for the *same* q = e^{i pi/p}
used everywhere else in this package (q itself, not just q^2, still
needs to be an honest primitive 2p'th root for 1/(q - q^-1) in [E, F] to
make sense -- see hopfsym.qring's docstring -- so the coefficient ring
is still Q(zeta_{2p}), unchanged from ``QuantumSl2Quasi``). Setting
K^p = 1 (e1 = 0, e0 = 1) in ``QuantumSl2Quasi``'s general-t formulas
collapses them to exactly the t-independent formulas above (the e1
terms vanish, and the associator Phi = 1(x)1(x)1 + e1(x)e1(x)(...)
becomes trivial) -- so this class can equally be understood as
"``QuantumSl2Quasi`` with e1 = 0", though it is implemented standalone
per this package's "each algebra hand-writes its own normal-form
reduction" convention (see CLAUDE.md), not by subclassing or reusing
``QuantumSl2Quasi``'s code.

Per the paper (end of Section 4.1), ``\UresSL2`` itself (K^{2p} = 1) is
*not* braidable -- no R-matrix exists for it. Surprisingly, that no-go
result does not survive the K^p = 1 quotient: this class *does* have a
universal R-matrix (``r_matrix``), and from it a monodromy element
(``monodromy``), a Drinfeld element (``drinfeld``), and a ribbon element
(``ribbon``), all verified against the same axioms as
``QuantumSl2Quasi``'s (``axioms.check_r_matrix_intertwiner``,
``check_hexagon`` -- trivially, since Phi = 1 here -- and
``check_ribbon``). This is not a contradiction: the paper's no-go
statement is specifically about the K^{2p} = 1 algebra, which this
class is a proper quotient of, not a restatement of it.

Where these formulas come from: every one of them is ``QuantumSl2Quasi``'s
corresponding formula, pushed through the K^p = 1 quotient map
pi: (a, b, c) |-> (a, b, c mod p) (verified computationally against that
projection before being written out here -- see the git history / dev
notes for the derivation). Concretely:

- ``r_matrix``: projecting R_t's four-term bracket
  ``1 + q^{tr} + q^{-t(n+s)} + q^{t^2/2+tr-t(n+s)}`` collapses it to the
  constant 4 (the other three terms' t-dependence cancels exactly against
  the two choices s = s' or s'+p, r = r' or r'+p) -- so the result is
  manifestly t-independent and needs no q^{1/2} at all, unlike
  ``QuantumSl2Quasi.r_matrix()``.
- ``monodromy``: R_21.R, verbatim the same construction as
  ``QuantumSl2Quasi.monodromy`` -- free once r_matrix is right, since
  projection commutes with the algebra product.
- ``drinfeld``: with Phi trivial, the general 5-fold-tensor Drinfeld
  formula in ``QuantumSl2Quasi.drinfeld`` collapses to the classical
  quasitriangular-Hopf-algebra formula u = sum S(r2).r1 for
  R = sum r1 (x) r2 -- no Phi/beta bookkeeping needed at all.
- ``ribbon``: unlike the other three, this one resisted a clean
  by-hand closed form (the K^p = 1 quotient of the Gauss-sum exponent is
  genuinely parity-in-p-dependent), so it's implemented as *literally the
  same sum* as ``QuantumSl2Quasi.ribbon`` -- same Gauss sum, same
  Q(zeta_{4p}) intermediate field -- just with the final K-exponent
  reduced mod p instead of mod 2p (this is exactly what projecting would
  do, since add_term merges the j and j+p terms automatically). Confirmed
  computationally to agree with pi(QuantumSl2Quasi(p, t).ribbon()) for
  p up to 5 and several t. The field only *looks* bigger than necessary;
  every coefficient that comes out is actually already in the same
  Q(zeta_{2p}) as everything else here, but there's no clean way to see
  that without redoing the Gauss-sum derivation for this quotient, so it
  isn't asserted -- CycloNum's auto-widening (see qring.py) makes this a
  non-issue for combining with the rest of the algebra either way.
- ``f_element``: with Phi trivial, the general formula in
  ``QuantumSl2Quasi.f_element`` collapses to F = 1 (x) 1 -- the standard
  fact that (S (x) S) . flip . Delta = Delta . S on the nose for an
  honest Hopf algebra, no twisting element needed.
"""

from __future__ import annotations

from ..algebra import QuasiHopfAlgebra
from ..element import Element, TensorKey, tensor
from ..qring import CycloNum
from ..unicode_fmt import TENSOR, superscript

# A basis key is a triple (a, b, c) representing E^a F^b K^c,
# 0 <= a, b, c < p.
BasisKey = tuple

# Token letters used by multiply_basis/_reduce_word, in the same order as
# a BasisKey's positions (index 0 = "E", 1 = "F", 2 = "K") -- the one
# place that correspondence is written down explicitly, rather than left
# implicit-by-convention at every call site.
_LETTERS = ("E", "F", "K")


class RestrictedSl2(QuasiHopfAlgebra):
    """U_res sl(2) at a primitive 2p'th root of unity, with K^p = 1."""

    def __init__(self, p: int):
        if p < 2:
            raise ValueError("need p >= 2")
        self.p = p
        self._comm_ef_cache = {}
        self._mul_basis_cache = {}
        self._qfact_cache = {}
        self._comul_power_cache = {"E": {}, "F": {}, "K": {}}
        self._antipode_power_cache = {"E": {}, "F": {}}
        self._r_matrix_cache = None
        self._monodromy_cache = None
        self._drinfeld_cache = None
        self._ribbon_cache = None
        self._f_element_cache = None

    def q(self, k: int) -> CycloNum:
        """q**k, as an element of Q(zeta_{2p}) -- same q = e^{i pi/p} as
        QuantumSl2Quasi, even though K itself only has order p here (see
        module docstring for why q still needs to be a 2p'th root)."""
        return CycloNum.power(2 * self.p, k)

    def q_half(self, two_k: int) -> CycloNum:
        """q**(two_k/2), as an element of Q(zeta_{4p}) -- only needed by
        ``ribbon`` (see its docstring); every other structure map here
        stays in Q(zeta_{2p})."""
        return CycloNum.power(4 * self.p, two_k)

    def _qnum(self, a: int) -> CycloNum:
        return (self.q(a) - self.q(-a)) / (self.q(1) - self.q(-1))

    def _qfact(self, a: int) -> CycloNum:
        cached = self._qfact_cache.get(a)
        if cached is not None:
            return cached
        result = CycloNum.one(2 * self.p) if a == 0 else self._qfact(a - 1) * self._qnum(a)
        self._qfact_cache[a] = result
        return result

    # -- basic data -----------------------------------------------------
    def basis(self):
        p = self.p
        return [(a, b, c) for a in range(p) for b in range(p) for c in range(p)]

    def unit(self) -> Element:
        return Element.basis((0, 0, 0))

    @property
    def E(self) -> Element:
        """The generator E, as a tagged Element (see Element.__mul__) --
        e.g. ``alg.E * alg.F`` is ``alg.mul(alg.E, alg.F)``."""
        return self.elt((1, 0, 0))

    @property
    def F(self) -> Element:
        """The generator F, tagged -- see ``E``."""
        return self.elt((0, 1, 0))

    @property
    def K(self) -> Element:
        """The generator K, tagged -- see ``E``."""
        return self.elt((0, 0, 1))

    # -- product ----------------------------------------------------------
    def multiply_basis(self, b1: BasisKey, b2: BasisKey) -> Element:
        key = (b1, b2)
        cached = self._mul_basis_cache.get(key)
        if cached is not None:
            return cached
        tokens = [(letter, exp) for letter, exp in zip(_LETTERS, b1)] + [
            (letter, exp) for letter, exp in zip(_LETTERS, b2)
        ]
        result = self._reduce_word(tokens)
        self._mul_basis_cache[key] = result
        return result

    def _reduce_word(self, tokens) -> Element:
        """Reduce a list of (letter, exponent) tokens to an Element in the
        normal-form basis E^a F^b K^c, 0 <= a, b, c < p -- identical in
        structure to QuantumSl2Quasi._reduce_word, except K wraps mod p
        instead of mod 2p (and there is no e0/e1 twist anywhere else in
        this algebra to worry about)."""
        p = self.p
        tokens = [t for t in tokens if t[1] != 0]

        # E^p = 0 = F^p.
        for letter, exp in tokens:
            if letter in ("E", "F") and exp >= p:
                return Element.zero()

        for i in range(len(tokens) - 1):
            (l1, e1), (l2, e2) = tokens[i], tokens[i + 1]

            # X^m X^n = X^(m+n), same generator adjacent.
            if l1 == l2:
                new_tokens = tokens[:i] + [(l1, e1 + e2)] + tokens[i + 2:]
                return self._reduce_word(new_tokens)

            if l1 == "K" and l2 == "E":
                # K^m E^n = q^{2mn} E^n K^m  (from K E K^-1 = q^2 E)
                coeff = self.q(2 * e1 * e2)
                new_tokens = tokens[:i] + [("E", e2), ("K", e1)] + tokens[i + 2:]
                return coeff * self._reduce_word(new_tokens)

            if l1 == "K" and l2 == "F":
                # K^m F^n = q^{-2mn} F^n K^m  (from K F K^-1 = q^-2 F)
                coeff = self.q(-2 * e1 * e2)
                new_tokens = tokens[:i] + [("F", e2), ("K", e1)] + tokens[i + 2:]
                return coeff * self._reduce_word(new_tokens)

            if l1 == "F" and l2 == "E":
                # F^m E^n = E^n F^m - [E^n, F^m]
                # (from [E, F] = (K - K^-1)/(q - q^-1))
                swapped = tokens[:i] + [("E", e2), ("F", e1)] + tokens[i + 2:]
                commutator = self._comm_ef(e2, e1)
                correction = self._sandwich(tokens[:i], commutator, tokens[i + 2:])
                return self._reduce_word(swapped) - correction

        # No more inversions or merges left: word is E^a F^b K^c already
        # (K^p = 1, so c wraps mod p; E^p = F^p = 0 already ruled out above).
        exps = {letter: 0 for letter in _LETTERS}
        for letter, exp in tokens:
            exps[letter] += exp
        a, b, c = (exps[letter] for letter in _LETTERS)
        c %= p
        if a >= p or b >= p:
            return Element.zero()
        return Element.basis((a, b, c))

    def _sandwich(self, prefix_tokens, middle: Element, suffix_tokens) -> Element:
        left = self._reduce_word(prefix_tokens) if prefix_tokens else self.unit()
        right = self._reduce_word(suffix_tokens) if suffix_tokens else self.unit()
        return self.mul(self.mul(left, middle), right)

    def _comm_ef(self, m: int, n: int) -> Element:
        """[E^m, F^n], same recursion as QuantumSl2Quasi._comm_ef (the
        relation [E, F] = (K - K^-1)/(q - q^-1) doesn't involve K's
        order, only K^{+-1} themselves)."""
        key = (m, n)
        if key in self._comm_ef_cache:
            return self._comm_ef_cache[key]

        if m == 1 and n == 1:
            p = self.p
            K = Element.basis((0, 0, 1))
            Kinv = Element.basis((0, 0, p - 1))
            q = self.q(1)
            qinv = self.q(-1)
            result = (K - Kinv) * (1 / (q - qinv))
        elif m == 1:
            F1 = Element.basis((0, 1, 0))
            Fnm1 = Element.basis((0, n - 1, 0))
            result = self.mul(F1, self._comm_ef(1, n - 1)) + self.mul(self._comm_ef(1, 1), Fnm1)
        else:
            E1 = Element.basis((1, 0, 0))
            Emm1 = Element.basis((m - 1, 0, 0))
            result = self.mul(E1, self._comm_ef(m - 1, n)) + self.mul(self._comm_ef(1, n), Emm1)

        self._comm_ef_cache[key] = result
        return result

    # -- coproduct --------------------------------------------------------
    def _comul_E1(self) -> Element:
        return tensor(Element.basis((1, 0, 0)), Element.basis((0, 0, 1))) + tensor(
            self.unit(), Element.basis((1, 0, 0))
        )

    def _comul_F1(self) -> Element:
        return tensor(Element.basis((0, 1, 0)), self.unit()) + tensor(
            Element.basis((0, 0, self.p - 1)), Element.basis((0, 1, 0))
        )

    def _comul_K1(self) -> Element:
        K1 = Element.basis((0, 0, 1))
        return tensor(K1, K1)

    def comul(self, elem: Element) -> Element:
        result = Element()
        for (a, b, c), coeff in elem.terms.items():
            result = result + coeff * self._comul_basis(a, b, c)
        return result

    def _comul_generator_power(self, letter: str, k: int) -> Element:
        """Delta(g)^k, built up incrementally and cached -- see
        QuantumSl2Quasi._comul_generator_power for why this matters for
        performance."""
        cache = self._comul_power_cache[letter]
        if k in cache:
            return cache[k]
        if k == 0:
            result = tensor(self.unit(), self.unit())
        else:
            from ..element import tensor_mul

            generator1 = {"E": self._comul_E1, "F": self._comul_F1, "K": self._comul_K1}[letter]()
            result = tensor_mul(self, self._comul_generator_power(letter, k - 1), generator1)
        cache[k] = result
        return result

    def _comul_basis(self, a: int, b: int, c: int) -> Element:
        from ..element import tensor_mul

        eE = self._comul_generator_power("E", a)
        eF = self._comul_generator_power("F", b)
        eK = self._comul_generator_power("K", c)
        return tensor_mul(self, tensor_mul(self, eE, eF), eK)

    # -- counit -------------------------------------------------------------
    def counit(self, elem: Element):
        total = CycloNum.zero(2 * self.p)
        for (a, b, c), coeff in elem.terms.items():
            if a == 0 and b == 0:
                total = total + coeff
        return total

    # -- antipode -------------------------------------------------------------
    def _antipode_E1(self) -> Element:
        EKinv = Element.basis((1, 0, self.p - 1))
        return -EKinv

    def _antipode_F1(self) -> Element:
        K = Element.basis((0, 0, 1))
        F = Element.basis((0, 1, 0))
        return -self.mul(K, F)

    def _antipode_power(self, letter: str, m: int) -> Element:
        cache = self._antipode_power_cache[letter]
        if m in cache:
            return cache[m]
        if m == 0:
            result = self.unit()
        else:
            generator1 = self._antipode_E1() if letter == "E" else self._antipode_F1()
            result = self.mul(generator1, self._antipode_power(letter, m - 1))
        cache[m] = result
        return result

    def antipode(self, elem: Element) -> Element:
        result = Element()
        for (a, b, c), coeff in elem.terms.items():
            result = result + coeff * self._antipode_basis(a, b, c)
        return result

    def _antipode_basis(self, a: int, b: int, c: int) -> Element:
        sK = Element.basis((0, 0, (-c) % self.p))
        sF = self._antipode_power("F", b)
        sE = self._antipode_power("E", a)
        return self.mul(self.mul(sK, sF), sE)

    # -- associator and evaluation/coevaluation elements (all trivial) ----
    def associator(self) -> Element:
        one = self.unit()
        return tensor(tensor(one, one), one)

    def associator_inv(self) -> Element:
        return self.associator()

    def alpha(self) -> Element:
        return self.unit()

    def beta(self) -> Element:
        return self.unit()

    # -- R-matrix, monodromy, Drinfeld and ribbon elements, "F" element ------
    # See the module docstring ("Where these formulas come from") for the
    # derivation of each -- all four are QuantumSl2Quasi's corresponding
    # construction pushed through the K^p = 1 quotient map.
    def r_matrix(self) -> Element:
        r"""The universal R-matrix, an element of H (x) H:

            R = 1/p sum_{n=0}^{p-1} sum_{s,r=0}^{p-1}
                (q-q^-1)^n/[n]! * q^{n(n-1)/2 + 2n(s-r) - 2sr} *
                E^n K^s (x) F^n K^r

        Entirely within Q(zeta_{2p}) -- no t-dependence, no q^{1/2}
        needed (contrast QuantumSl2Quasi.r_matrix()).
        """
        if self._r_matrix_cache is not None:
            return self._r_matrix_cache

        from fractions import Fraction

        p = self.p
        result = Element()
        for n in range(p):
            coeff_n = (self.q(1) - self.q(-1)) ** n / self._qfact(n)
            for s in range(p):
                for r in range(p):
                    exp_ = n * (n - 1) // 2 + 2 * n * (s - r) - 2 * s * r
                    total = coeff_n * self.q(exp_) * Fraction(1, p)
                    result.add_term(TensorKey(((n, 0, s), (0, n, r))), total)

        self._r_matrix_cache = result
        return result

    def monodromy(self) -> Element:
        """The monodromy matrix M = R_21 . R."""
        if self._monodromy_cache is not None:
            return self._monodromy_cache
        from ..element import flip, tensor_mul

        R = self.r_matrix()
        result = tensor_mul(self, flip(R), R)
        self._monodromy_cache = result
        return result

    def drinfeld(self) -> Element:
        """The Drinfeld element u = sum S(r2) . r1, for R = sum r1 (x) r2
        -- the classical formula for an (honest) quasitriangular Hopf
        algebra (Phi trivial collapses the general quasi-Hopf formula to
        this, see module docstring)."""
        if self._drinfeld_cache is not None:
            return self._drinfeld_cache

        result = Element()
        for key, c in self.r_matrix().terms.items():
            r1, r2 = key
            term = self.mul(self.antipode(Element.basis(r2)), Element.basis(r1))
            for k2, c2 in term.terms.items():
                result.add_term(k2, c * c2)

        self._drinfeld_cache = result
        return result

    def ribbon(self) -> Element:
        r"""The ribbon element, an element of H:

            v = (1-i)/(2 sqrt(p)) * sum_{n=0}^{p-1} sum_{j in Z_2p}
                (q-q^-1)^n/[n]! * q^{n(j-1/2) + 1/2(j+p+1)^2} * F^n E^n K^j

        Literally QuantumSl2Quasi.ribbon()'s formula (see its docstring
        for the exact-Gauss-sum construction of the prefactor -- unchanged
        here), except the K-exponent is reduced mod p instead of mod 2p;
        see this module's docstring for why a from-scratch closed form
        wasn't used instead.
        """
        if self._ribbon_cache is not None:
            return self._ribbon_cache

        from fractions import Fraction

        p = self.p
        N = 4 * p
        gauss_sum = sum((self.q_half(-a * a) for a in range(2 * p)), CycloNum.zero(N))
        prefactor = gauss_sum * Fraction(1, 2 * p)

        result = Element()
        for n in range(p):
            coeff_n = ((self.q(1) - self.q(-1)) ** n / self._qfact(n)).embed(N)
            for j in range(2 * p):
                doubled_exp = 2 * n * j - n + (j + p + 1) ** 2
                scalar = prefactor * self.q_half(doubled_exp) * coeff_n
                basis_elem = self._reduce_word([("F", n), ("E", n), ("K", j % p)])
                for k, c in basis_elem.terms.items():
                    result.add_term(k, scalar * c)

        self._ribbon_cache = result
        return result

    def f_element(self) -> Element:
        """The element F relating Delta and S -- trivial (F = 1 (x) 1)
        since Phi is trivial here; see module docstring."""
        if self._f_element_cache is not None:
            return self._f_element_cache
        one = self.unit()
        self._f_element_cache = tensor(one, one)
        return self._f_element_cache

    # -- readable output ---------------------------------------------------
    def pretty(self, elem: Element) -> str:
        """Human-readable string, e.g. ``"2*E² F K + (1-q)*K""`` -- see
        QuantumSl2Quasi.pretty for the analogous formatter (this one is
        simpler: only one cyclotomic field, Q(zeta_{2p}), is ever in
        play)."""
        if not elem.terms:
            return "0"
        rendered = []
        for key, coeff in sorted(elem.terms.items(), key=lambda kv: kv[0]):
            coeff_str = self._format_coeff(coeff)
            if coeff_str == "0":
                continue
            key_str = self._format_key(key)
            if key_str == "1":
                rendered.append(coeff_str)
            elif coeff_str == "1":
                rendered.append(key_str)
            elif coeff_str == "-1":
                rendered.append(f"-{key_str}")
            elif " + " in coeff_str or " - " in coeff_str:
                rendered.append(f"({coeff_str})*{key_str}")
            else:
                rendered.append(f"{coeff_str}*{key_str}")
        if not rendered:
            return "0"
        out = rendered[0]
        for term in rendered[1:]:
            out += f" - {term[1:]}" if term.startswith("-") else f" + {term}"
        return out

    def _format_key(self, key) -> str:
        if isinstance(key, TensorKey):
            return f" {TENSOR} ".join(self._format_key(k) for k in key)
        a, b, c = key
        factors = [
            f"{letter}{superscript(exp)}" if exp > 1 else letter
            for letter, exp in (("E", a), ("F", b), ("K", c))
            if exp != 0
        ]
        return " ".join(factors) if factors else "1"

    def _format_coeff(self, c) -> str:
        if isinstance(c, CycloNum):
            return self._format_cyclonum(c)
        return str(c)

    def _format_cyclonum(self, c: CycloNum) -> str:
        if c.n is None:
            return str(c.poly.coeffs[0])
        if c.n == 2 * self.p:
            power = lambda k: "" if k == 0 else ("q" if k == 1 else f"q{superscript(k)}")
        elif c.n == 4 * self.p:
            # x = zeta_{4p} = q**(1/2) -- only ribbon() ever produces this.
            def power(k):
                if k == 0:
                    return ""
                if k % 2 == 0:
                    return "q" if k == 2 else f"q{superscript(k // 2)}"
                return f"q{superscript('(1/2)')}" if k == 1 else f"q{superscript(f'({k}/2)')}"
        else:  # pragma: no cover - fallback for an unanticipated field
            symbol = f"zeta_{c.n}"
            power = lambda k: "" if k == 0 else (symbol if k == 1 else f"{symbol}{superscript(k)}")
        terms = []
        for k, coeff in enumerate(c.poly.coeffs):
            if coeff == 0:
                continue
            p_str = power(k)
            if p_str == "":
                terms.append(f"{coeff}")
            elif coeff == 1:
                terms.append(p_str)
            elif coeff == -1:
                terms.append(f"-{p_str}")
            else:
                terms.append(f"{coeff}*{p_str}")
        if not terms:
            return "0"
        out = terms[0]
        for t in terms[1:]:
            out += f" - {t[1:]}" if t.startswith("-") else f" + {t}"
        return out
