r"""The symplectic fermion ribbon quasi-Hopf algebra Q(N, beta).

This is a direct port of the algebra data given in Section 3.1
("Definition of Q") of

    V. Farsad, A. M. Gainutdinov, I. Runkel, "The symplectic fermion
    ribbon quasi-Hopf algebra and the SL(2,Z)-action on its centre",
    arXiv:1706.08164, building on Davydov-Runkel's category of N pairs
    of symplectic fermions (arXiv:1207.3611).

(``~/ClaudeFolder/HopfAlgebraTesting/arXiv-1706.08164v3/SF-qHopf-revised.tex``
on Ingo's machine -- a sibling checkout to this repo, *not* copied in
here, see ``reference/README.md`` -- is the ground truth this was
transcribed from. There is no Mathematica reference for this algebra,
so verification here leans on the paper's own Remark right after the
definition, see below, plus the generic axiom checks in ``axioms.py``.)

Only the quasi-Hopf data (product, coproduct, counit, associator,
antipode, evaluation/coevaluation elements) is ported here -- the
R-matrix and ribbon element from the same section are not yet ported.

## Generators and relations

As a C-algebra, Q(N, beta) is generated by K and f_i^+-, i = 1..N, with
(anticommutator) relations::

    {f_i^+-, K} = 0,           {f_i^+, f_j^-} = delta_ij * e1
    {f_i^eps, f_j^eps} = 0,    K^4 = 1

where {x, y} = xy + yx, and e0 = (1+K^2)/2, e1 = (1-K^2)/2 are central
idempotents (so in particular (f_i^eps)^2 = 0: every generator is
nilpotent, unlike E/F in ``QuantumSl2Quasi``). A basis is::

    (f_1^+)^{n_1^+} (f_1^-)^{n_1^-} ... (f_N^+)^{n_N^+} (f_N^-)^{n_N^-} K^n,
    n_i^+- in {0, 1},  n in Z_4

giving dimension 2^{2N+2}.

## Coefficient ring

Unlike ``QuantumSl2Quasi``/``RestrictedSl2`` (where the field's degree
scales with the algebra's own parameter p), here the two scalars that
ever appear -- i (the imaginary unit) and beta (the algebra's second
parameter, with beta^4 = (-1)^N) -- both have order dividing 8
regardless of N: beta^4 = (-1)^N means beta^8 = 1 always, and i = zeta_8^2.
So a single fixed field, Q(zeta_8) (``hopfsym.qring.CycloNum`` with
n=8), suffices for every N. beta is specified to the constructor as an
exponent ``beta_power`` with beta = zeta_8^beta_power; the constraint
beta^4 = (-1)^N becomes beta_power % 2 == N % 2 (matching the paper's
"four possible choices of beta" for given N: the four residues of the
right parity mod 8).

## Verification strategy (no Mathematica reference exists)

Remark right after eq:Q-antipode-def in the paper gives two independent,
directly checkable facts used here as regression tests (see
tests/test_symplectic_fermion.py):

- For N even and beta^2 = 1: Salpha = Sbeta = 1 and Phi is trivial (so Q
  is an honest Hopf algebra in that case).
- The explicit formulas for (Delta x id)(Delta(f_i^-)) and
  (id x Delta)(Delta(f_i^-)) (general N) -- these differ only in the
  sign of one idempotent term (-(-1)^N vs -1), exactly the Phi-twist
  ``check_twisted_coassociativity`` checks generically; comparing
  against these two explicit formulas directly checks ``comul`` in
  isolation, independent of whether ``associator`` is also right.
"""

from __future__ import annotations

from fractions import Fraction
from itertools import product as _iproduct

from ..algebra import QuasiHopfAlgebra
from ..element import Element, TensorKey, tensor, tensor_mul
from ..qring import CycloNum
from ..unicode_fmt import TENSOR, subscript, superscript

# A basis key is (bits, k): bits is a tuple of 2N 0/1 entries (bits[2*i]
# = whether f_{i+1}^+ is present, bits[2*i+1] = whether f_{i+1}^- is
# present, 0-indexed i), and k in {0,1,2,3} is K's exponent.
BasisKey = tuple


class SymplecticFermionQ(QuasiHopfAlgebra):
    """Q(N, beta), the symplectic fermion ribbon quasi-Hopf algebra, over
    Q(zeta_8) (beta = zeta_8**beta_power, i = zeta_8**2)."""

    def __init__(self, N: int, beta_power: int):
        if N < 1:
            raise ValueError("need N >= 1")
        beta_power %= 8
        if beta_power % 2 != N % 2:
            raise ValueError(
                f"beta_power must have the same parity as N (beta^4 = (-1)^N "
                f"requires beta_power % 2 == N % 2); got N={N}, beta_power={beta_power}"
            )
        self.N = N
        self.beta_power = beta_power
        self._mul_basis_cache = {}
        self._comul_f_cache = {}
        self._comul_K_power_cache = {}
        self._antipode_f_cache = {}
        self._antipode_K_power_cache = {}
        self._antipode_basis_cache = {}
        self._comul_basis_cache = {}

        # e0 = (1+K^2)/2, e1 = (1-K^2)/2: central idempotents, used all
        # over the structure maps below -- computed once here (tagged,
        # see Element.__mul__) rather than re-derived on every call, and
        # used directly as self.e0/self.e1 everywhere internally too
        # (safe to tag: self.mul(...) always retags its own result with
        # self regardless of its arguments' tags, and tensor(...) always
        # builds a fresh untagged Element, so tagging e0/e1 can't leak an
        # incorrect tag into a H^{(x)n} result like Phi or comul(...)).
        one = self.unit()
        K2 = self._K(2)
        self.e0 = Fraction(1, 2) * (one + K2)
        self.e1 = Fraction(1, 2) * (one - K2)
        self.e0.alg = self
        self.e1.alg = self

    # -- scalars --------------------------------------------------------
    def i(self) -> CycloNum:
        """The imaginary unit, as an element of Q(zeta_8)."""
        return CycloNum.power(8, 2)

    def beta_scalar(self) -> CycloNum:
        """The algebra parameter beta = zeta_8**beta_power, as a scalar
        in Q(zeta_8). Deliberately *not* called ``beta()`` -- that name
        is taken by the QuasiHopfAlgebra interface method returning the
        coevaluation element Sbeta (a different thing entirely, matching
        the paper's own notation clash between the parameter "beta" and
        the element "Salpha/Sbeta")."""
        return CycloNum.power(8, self.beta_power)

    # -- basic data -----------------------------------------------------
    def basis(self):
        N = self.N
        return [(bits, k) for bits in _iproduct((0, 1), repeat=2 * N) for k in range(4)]

    def unit(self) -> Element:
        return Element.basis(((0,) * (2 * self.N), 0))

    def _K(self, exp: int = 1) -> Element:
        return Element.basis(((0,) * (2 * self.N), exp % 4))

    def _f(self, pos: int) -> Element:
        bits = [0] * (2 * self.N)
        bits[pos] = 1
        return Element.basis((tuple(bits), 0))

    @property
    def K(self) -> Element:
        """The generator K, tagged (see Element.__mul__) -- e.g.
        ``alg.K ** 4 == alg.unit()``."""
        e = self._K(1)
        e.alg = self
        return e

    def f(self, i: int, eps: str) -> Element:
        """The generator f_i^eps (eps = '+' or '-'), tagged -- e.g.
        ``alg.f(1, '+') * alg.f(1, '-')`` is ``alg.mul(...)``. i is
        1-indexed, matching the paper's f_i^+- notation (built on top of
        the position-indexed ``_f``, which stays as the untagged,
        0-indexed helper used internally by ``_comul_f``/``_antipode_f``)."""
        if eps not in ("+", "-"):
            raise ValueError("eps must be '+' or '-'")
        if not 1 <= i <= self.N:
            raise ValueError(f"i must be between 1 and N={self.N}")
        pos = 2 * (i - 1) + (0 if eps == "+" else 1)
        e = self._f(pos)
        e.alg = self
        return e

    # -- product ----------------------------------------------------------
    def multiply_basis(self, b1: BasisKey, b2: BasisKey) -> Element:
        key = (b1, b2)
        cached = self._mul_basis_cache.get(key)
        if cached is not None:
            return cached
        tokens = self._key_to_tokens(b1) + self._key_to_tokens(b2)
        result = self._reduce_word(tokens)
        self._mul_basis_cache[key] = result
        return result

    def _key_to_tokens(self, key: BasisKey):
        bits, k = key
        tokens = [("f", pos) for pos, b in enumerate(bits) if b]
        if k % 4 != 0:
            tokens.append(("K", k % 4))
        return tokens

    def _reduce_word(self, tokens) -> Element:
        """Reduce a list of ("f", pos) / ("K", exp) tokens to an Element
        in the normal-form basis (all f's present at most once, sorted
        by position, then K). This is *the* place the algebra's
        (anticommutator) relations live; every other structure map only
        ever calls self.mul, which bottoms out here -- same overall
        design as QuantumSl2Quasi._reduce_word, but the relations here
        are genuinely different: anticommutation (sign -1, not a
        q-power) between distinct generators, nilpotency
        ((f_i^eps)^2 = 0) instead of E^p = 0, and a *central-idempotent*
        correction term e1 (not a recursively-built commutator) when two
        conjugate generators f_i^+, f_i^- meet in the wrong order.
        """
        tokens = [t for t in tokens if not (t[0] == "K" and t[1] % 4 == 0)]

        for idx in range(len(tokens) - 1):
            t1, t2 = tokens[idx], tokens[idx + 1]

            if t1[0] == "K" and t2[0] == "K":
                # K^a K^b = K^(a+b mod 4)  (from K^4 = 1)
                merged = (t1[1] + t2[1]) % 4
                new_tokens = tokens[:idx] + ([("K", merged)] if merged else []) + tokens[idx + 2:]
                return self._reduce_word(new_tokens)

            if t1[0] == "K" and t2[0] == "f":
                # K^a f = (-1)^a f K^a  (from {f_i^+-, K} = 0)
                sign = -1 if t1[1] % 2 else 1
                new_tokens = tokens[:idx] + [t2, t1] + tokens[idx + 2:]
                result = self._reduce_word(new_tokens)
                return sign * result

            if t1[0] == "f" and t2[0] == "f":
                pos1, pos2 = t1[1], t2[1]
                if pos1 == pos2:
                    # (f_i^eps)^2 = 0  (from {f_i^eps, f_j^eps} = 0 at i=j)
                    return Element.zero()
                i1, i2 = pos1 // 2, pos2 // 2
                if i1 == i2:
                    # same i, opposite sign (pos1 != pos2 but same pair):
                    # correct order is '+' (even pos) before '-' (odd pos).
                    if pos1 < pos2:
                        continue  # already correct, keep scanning
                    # wrong order: f_i^- f_i^+ = e1 - f_i^+ f_i^-
                    # (from {f_i^+, f_j^-} = delta_ij * e1 at i=j)
                    prefix, suffix = tokens[:idx], tokens[idx + 2:]
                    correction = self._sandwich(prefix, self.e1, suffix)
                    swapped = prefix + [("f", pos2), ("f", pos1)] + suffix
                    return correction - self._reduce_word(swapped)
                if pos1 > pos2:
                    # different i, out of order: pure anticommutation, no
                    # correction term -- both {f_i^eps,f_j^eps} = 0 (same
                    # sign) and {f_i^+,f_j^-} = delta_ij*e1 (opposite sign)
                    # collapse to this once i != j, since delta_ij = 0 either way.
                    new_tokens = tokens[:idx] + [t2, t1] + tokens[idx + 2:]
                    return -1 * self._reduce_word(new_tokens)
                continue  # different i, already in order

        # No more inversions: tokens are already sorted f's (each once)
        # followed by at most one K token.
        bits = [0] * (2 * self.N)
        k = 0
        for t in tokens:
            if t[0] == "f":
                bits[t[1]] = 1
            else:
                k = t[1] % 4
        return Element.basis((tuple(bits), k))

    def _sandwich(self, prefix_tokens, middle: Element, suffix_tokens) -> Element:
        left = self._reduce_word(prefix_tokens) if prefix_tokens else self.unit()
        right = self._reduce_word(suffix_tokens) if suffix_tokens else self.unit()
        return self.mul(self.mul(left, middle), right)

    # -- coproduct --------------------------------------------------------
    def _omega(self, sign: int) -> Element:
        """omega_+- = (e0 +- i*e1) . K."""
        combo = self.e0 + (sign * self.i()) * self.e1
        return self.mul(combo, self._K(1))

    def _comul_K1(self) -> Element:
        """Delta(K) = K (x) K - (1+(-1)^N) (e1.K) (x) (e1.K)."""
        e1K = self.mul(self.e1, self._K(1))
        K = self._K(1)
        correction = (1 + (-1) ** self.N) * tensor(e1K, e1K)
        return tensor(K, K) - correction

    def _comul_K_power(self, k: int) -> Element:
        cached = self._comul_K_power_cache.get(k)
        if cached is not None:
            return cached
        if k == 0:
            result = tensor(self.unit(), self.unit())
        else:
            result = tensor_mul(self, self._comul_K_power(k - 1), self._comul_K1())
        self._comul_K_power_cache[k] = result
        return result

    def _comul_f(self, pos: int) -> Element:
        """Delta(f_i^+-) = f_i^+- (x) 1 + omega_+- (x) f_i^+-, for the
        generator at bit position pos (+ if pos even, - if pos odd)."""
        cached = self._comul_f_cache.get(pos)
        if cached is not None:
            return cached
        sign = 1 if pos % 2 == 0 else -1
        f = self._f(pos)
        result = tensor(f, self.unit()) + tensor(self._omega(sign), f)
        self._comul_f_cache[pos] = result
        return result

    def comul(self, elem: Element) -> Element:
        result = Element()
        for (bits, k), coeff in elem.terms.items():
            result = result + coeff * self._comul_basis(bits, k)
        return result

    def _comul_basis(self, bits, k) -> Element:
        key = (bits, k)
        cached = self._comul_basis_cache.get(key)
        if cached is not None:
            return cached
        result = None
        for pos, b in enumerate(bits):
            if b:
                factor = self._comul_f(pos)
                result = factor if result is None else tensor_mul(self, result, factor)
        Kfactor = self._comul_K_power(k)
        result = Kfactor if result is None else tensor_mul(self, result, Kfactor)
        self._comul_basis_cache[key] = result
        return result

    # -- counit -------------------------------------------------------------
    def counit(self, elem: Element):
        total = CycloNum.zero(8)
        for (bits, k), coeff in elem.terms.items():
            if not any(bits):
                total = total + coeff
        return total

    # -- antipode -------------------------------------------------------------
    def _antipode_K1(self) -> Element:
        """S(K) = (e0 + (-1)^N e1) . K."""
        combo = self.e0 + Fraction((-1) ** self.N) * self.e1
        return self.mul(combo, self._K(1))

    def _antipode_K_power(self, k: int) -> Element:
        cached = self._antipode_K_power_cache.get(k)
        if cached is not None:
            return cached
        result = self.unit() if k == 0 else self.mul(self._antipode_K1(), self._antipode_K_power(k - 1))
        self._antipode_K_power_cache[k] = result
        return result

    def _antipode_f(self, pos: int) -> Element:
        """S(f_i^+-) = f_i^+- . (e0 +- (-1)^N i e1) . K."""
        cached = self._antipode_f_cache.get(pos)
        if cached is not None:
            return cached
        sign = 1 if pos % 2 == 0 else -1
        combo = self.e0 + (sign * ((-1) ** self.N) * self.i()) * self.e1
        result = self.mul(self.mul(self._f(pos), combo), self._K(1))
        self._antipode_f_cache[pos] = result
        return result

    def antipode(self, elem: Element) -> Element:
        result = Element()
        for (bits, k), coeff in elem.terms.items():
            result = result + coeff * self._antipode_basis(bits, k)
        return result

    def _antipode_basis(self, bits, k) -> Element:
        """S(f_1^{e1}...f_last K^k) = S(K)^k . S(f_last) ... S(f_1)
        (S reverses order, same pattern as QuantumSl2Quasi._antipode_basis)."""
        key = (bits, k)
        cached = self._antipode_basis_cache.get(key)
        if cached is not None:
            return cached
        result = self._antipode_K_power(k)
        for pos in reversed(range(len(bits))):
            if bits[pos]:
                result = self.mul(result, self._antipode_f(pos))
        self._antipode_basis_cache[key] = result
        return result

    # -- associator and evaluation/coevaluation elements ------------------------
    def _assoc_third_factor(self, i_sign: int) -> Element:
        """(K^N - 1).e0 + (beta^2 (i_sign*i*K)^N - 1).e1, the third tensor
        leg of Phi (i_sign=+1) / Phi^-1 (i_sign=-1)."""
        one = self.unit()
        KN = self._K(self.N)
        term_a = self.mul(KN - one, self.e0)
        scalar = self.beta_scalar() ** 2 * (i_sign * self.i()) ** self.N
        bracket_b = scalar * KN - one
        term_b = self.mul(bracket_b, self.e1)
        return term_a + term_b

    def associator(self) -> Element:
        one = self.unit()
        term1 = tensor(tensor(one, one), one)
        term2 = tensor(tensor(self.e1, self.e1), self._assoc_third_factor(+1))
        return term1 + term2

    def associator_inv(self) -> Element:
        one = self.unit()
        term1 = tensor(tensor(one, one), one)
        term2 = tensor(tensor(self.e1, self.e1), self._assoc_third_factor(-1))
        return term1 + term2

    def alpha(self) -> Element:
        return self.unit()

    def beta(self) -> Element:
        """Sbeta = e0 + beta^2 (iK)^N e1."""
        scalar = self.beta_scalar() ** 2 * self.i() ** self.N
        return self.e0 + self.mul(scalar * self._K(self.N), self.e1)

    # -- readable output ---------------------------------------------------
    def pretty(self, elem: Element) -> str:
        """Human-readable string, e.g. ``"2*f₁⁺ f₁⁻ + (1-i)*K""``."""
        if not elem.terms:
            return "0"
        rendered = []
        for key, coeff in sorted(elem.terms.items(), key=lambda kv: kv[0]):
            coeff_str = self._format_coeff(coeff)
            if coeff_str == "0":
                continue
            key_str = self._format_key(key)
            if key_str == "1":
                rendered.append(coeff_str)
            elif coeff_str == "1":
                rendered.append(key_str)
            elif coeff_str == "-1":
                rendered.append(f"-{key_str}")
            elif " + " in coeff_str or " - " in coeff_str:
                rendered.append(f"({coeff_str})*{key_str}")
            else:
                rendered.append(f"{coeff_str}*{key_str}")
        if not rendered:
            return "0"
        out = rendered[0]
        for term in rendered[1:]:
            out += f" - {term[1:]}" if term.startswith("-") else f" + {term}"
        return out

    def _format_key(self, key) -> str:
        if isinstance(key, TensorKey):
            return f" {TENSOR} ".join(self._format_key(k) for k in key)
        bits, k = key
        parts = []
        for pos, b in enumerate(bits):
            if b:
                idx = pos // 2 + 1
                sign = "+" if pos % 2 == 0 else "-"
                parts.append(f"f{subscript(idx)}{superscript(sign)}")
        if k == 1:
            parts.append("K")
        elif k > 1:
            parts.append(f"K{superscript(k)}")
        return " ".join(parts) if parts else "1"

    def _format_coeff(self, c) -> str:
        if isinstance(c, CycloNum):
            return self._format_cyclonum(c)
        return str(c)

    def _format_cyclonum(self, c: CycloNum) -> str:
        if c.n is None:
            return str(c.poly.coeffs[0])

        zeta8 = f"ζ{subscript(8)}"  # zeta_8

        def power(k):
            if k == 0:
                return ""
            if k == 1:
                return zeta8
            if k == 2:
                return "i"
            return f"{zeta8}{superscript(k)}"

        terms = []
        for k, coeff in enumerate(c.poly.coeffs):
            if coeff == 0:
                continue
            p_str = power(k)
            if p_str == "":
                terms.append(f"{coeff}")
            elif coeff == 1:
                terms.append(p_str)
            elif coeff == -1:
                terms.append(f"-{p_str}")
            else:
                terms.append(f"{coeff}*{p_str}")
        if not terms:
            return "0"
        out = terms[0]
        for t in terms[1:]:
            out += f" - {t[1:]}" if t.startswith("-") else f" + {t}"
        return out
