r"""The symplectic fermion ribbon quasi-Hopf algebra Q(N, beta).

This is a direct port of the algebra data given in Section 3.1
("Definition of Q") of

    V. Farsad, A. M. Gainutdinov, I. Runkel, "The symplectic fermion
    ribbon quasi-Hopf algebra and the SL(2,Z)-action on its centre",
    arXiv:1706.08164, building on Davydov-Runkel's category of N pairs
    of symplectic fermions (arXiv:1207.3611).

(``~/ClaudeFolder/HopfAlgebraTesting/arXiv-1706.08164v3/SF-qHopf-revised.tex``
on Ingo's machine -- not part of this repo -- is the ground truth this
was transcribed from. There is no Mathematica reference for this
algebra, so verification here leans on the paper's own Remark right
after the definition, see below, plus the generic axiom checks in
``axioms.py``.)

The full ribbon quasi-Hopf structure is ported: product, coproduct,
counit, associator, antipode, evaluation/coevaluation elements, and (see
``r_matrix()``/``ribbon()``) the universal R-matrix and ribbon element
from the same section, verified exactly against ``axioms.check_all``
plus ``check_r_matrix_intertwiner``, ``check_hexagon``, ``check_ribbon``
and ``check_s_delta_compatibility`` across every valid (N, beta_power).

## Generators and relations

As a C-algebra, Q(N, beta) is generated by K and f_i^+-, i = 1..N, with
(anticommutator) relations::

    {f_i^+-, K} = 0,           {f_i^+, f_j^-} = delta_ij * e1
    {f_i^eps, f_j^eps} = 0,    K^4 = 1

where {x, y} = xy + yx, and e0 = (1+K^2)/2, e1 = (1-K^2)/2 are central
idempotents (so in particular (f_i^eps)^2 = 0: every generator is
nilpotent, unlike E/F in ``QuantumSl2Quasi``). A basis is::

    (f_1^+)^{n_1^+} (f_1^-)^{n_1^-} ... (f_N^+)^{n_N^+} (f_N^-)^{n_N^-} K^n,
    n_i^+- in {0, 1},  n in Z_4

giving dimension 2^{2N+2}.

## Coefficient ring

Unlike ``QuantumSl2Quasi``/``RestrictedSl2`` (where the field's degree
scales with the algebra's own parameter p), here the two scalars that
ever appear -- i (the imaginary unit) and beta (the algebra's second
parameter, with beta^4 = (-1)^N) -- both have order dividing 8
regardless of N: beta^4 = (-1)^N means beta^8 = 1 always, and i = zeta_8^2.
So a single fixed field, Q(zeta_8) (``hopfsym.qring.CycloNum`` with
n=8), suffices for every N. beta is specified to the constructor as an
exponent ``beta_power`` with beta = zeta_8^beta_power; the constraint
beta^4 = (-1)^N becomes beta_power % 2 == N % 2 (matching the paper's
"four possible choices of beta" for given N: the four residues of the
right parity mod 8).

## R-matrix and ribbon element

``r_matrix()``/``r_matrix_inv()`` and ``ribbon()``/``ribbon_inv()`` are
ported from eq:R+Riv/eq:ribbon+ribinv (Section 3.1), which give both
directions explicitly -- checked against each other by
``axioms.check_r_matrix_inverse``/``axioms.check_ribbon_inverse`` -- both
entirely within Q(zeta_8), unlike ``QuantumSl2Quasi``'s R-matrix/ribbon,
which need a field extension
(``embed()``) since q**(1/2) genuinely isn't in Q(zeta_{2p}); here both
scalars that appear (i, beta) already live in the algebra's one fixed
field. ``monodromy()``, ``drinfeld()`` and ``f_element()`` are *not*
overridden here -- they're provably generic (Phi/R/S/alpha/beta only, no
algebra-specific data), so they're provided for free by
``QuasiHopfAlgebra`` itself (see its docstring). The paper's own
"Some special elements of Q" section (Section 3.2) gives independent
closed forms for both, used as regression tests against these generic
implementations in tests/test_symplectic_fermion.py rather than
reimplemented here.

## Integral

``left_integral()`` is ported from eq:int-Q (Section 3.5), a two-sided
integral -- ``right_integral()`` just returns the same element -- checked
against its defining property by ``axioms.check_left_integral``/
``axioms.check_right_integral`` (the latter defined by multiplying the
other way round, not via a separate H^op algebra). This formula also
comes from a source outside the "R-matrix and ribbon element" section
above (arXiv:1812.10445, "Integrals and cointegrals"), which additionally
cites this same formula (Section "Example: symplectic fermion quasi-Hopf
algebra") and confirms that Q is unimodular.

## Cointegral

``modulus()`` is just the counit (Q being unimodular, see above).
``antipode_inv()`` (S^-1, from arXiv:1812.10445, stated right after its
eq (3.35)) and ``f_element_inv()`` (F^-1, obtained here by directly
inverting eq:def:F-Q's already-sourced formula block-by-block -- see its
own docstring) feed into ``QuasiHopfAlgebra``'s generic ``qR()``/
``pR()``/``qL()``/``pL()``/``U()``/``V()``/``Ucop()``/``Vcop()``, which
in turn are what ``left_cointegral()``/``right_cointegral()`` (ported
from eq (5.24)-(5.25) in the same paper's Section 5, also two-sided
here) get checked against by ``axioms.check_left_cointegral``/
``axioms.check_right_cointegral`` (Definition 3.5, paraphrasing
Bulacu-Caenepeel). The paper's own basis convention for its cointegral
formula (all +'s before all -'s) differs from this module's normal-form
ordering (interleaved, see "Generators and relations" above) by an
overall sign, (-1)^(N(N-1)/2) -- resolved empirically (not just derived
by hand) against ``check_left_cointegral``, see ``left_cointegral()``'s
docstring. This whole chain caught a real bug during development
(``f_element_inv()``'s formula) via ``check_left_cointegral`` genuinely
failing until it was fixed -- not a case of a vacuously-satisfied check.

## Verification strategy (no Mathematica reference exists)

Remark right after eq:Q-antipode-def in the paper gives two independent,
directly checkable facts used here as regression tests (see
tests/test_symplectic_fermion.py):

- For N even and beta^2 = 1: Salpha = Sbeta = 1 and Phi is trivial (so Q
  is an honest Hopf algebra in that case).
- The explicit formulas for (Delta x id)(Delta(f_i^-)) and
  (id x Delta)(Delta(f_i^-)) (general N) -- these differ only in the
  sign of one idempotent term (-(-1)^N vs -1), exactly the Phi-twist
  ``check_twisted_coassociativity`` checks generically; comparing
  against these two explicit formulas directly checks ``comul`` in
  isolation, independent of whether ``associator`` is also right.

The paper gives no comparable explicit remark to check the R-matrix or
ribbon element against directly, so those are verified purely via the
generic checks in ``axioms.py`` (``check_r_matrix_intertwiner``,
``check_hexagon``, ``check_ribbon``, ``check_s_delta_compatibility``),
run across every valid (N, beta_power) pair for N in {1,2,3} (see
tests/test_symplectic_fermion.py's ``BraidingTests``) -- weaker than an
independent closed-form cross-check, but every one of those four axioms
is a genuinely non-trivial identity a wrong transcription would very
likely fail (confirmed by deliberately breaking the R-matrix formula
during development and checking that ``check_hexagon``/``check_ribbon``
correctly caught it).
"""

from __future__ import annotations

from fractions import Fraction
from itertools import product as _iproduct

from ..algebra import QuasiHopfAlgebra
from ..element import Element, TensorKey, tensor
from ..qring import CycloNum
from ..unicode_fmt import TENSOR, subscript, superscript

# A basis key is (bits, k): bits is a tuple of 2N 0/1 entries (bits[2*i]
# = whether f_{i+1}^+ is present, bits[2*i+1] = whether f_{i+1}^- is
# present, 0-indexed i), and k in {0,1,2,3} is K's exponent.
BasisKey = tuple


class SymplecticFermionQ(QuasiHopfAlgebra):
    """Q(N, beta), the symplectic fermion ribbon quasi-Hopf algebra, over
    Q(zeta_8) (beta = zeta_8**beta_power, i = zeta_8**2)."""

    def __init__(self, N: int, beta_power: int):
        if N < 1:
            raise ValueError("need N >= 1")
        beta_power %= 8
        if beta_power % 2 != N % 2:
            raise ValueError(
                f"beta_power must have the same parity as N (beta^4 = (-1)^N "
                f"requires beta_power % 2 == N % 2); got N={N}, beta_power={beta_power}"
            )
        self.N = N
        self.beta_power = beta_power
        self._mul_basis_cache = {}
        self._comul_f_cache = {}
        self._comul_K_power_cache = {}
        self._antipode_f_cache = {}
        self._antipode_K_power_cache = {}
        self._antipode_basis_cache = {}
        self._antipode_inv_f_cache = {}
        self._antipode_inv_basis_cache = {}
        self._comul_basis_cache = {}
        self._r_matrix_cache = None
        self._r_matrix_inv_cache = None
        self._ribbon_cache = None
        self._ribbon_inv_cache = None
        self._left_integral_cache = None

        # e0 = (1+K^2)/2, e1 = (1-K^2)/2: central idempotents, used all
        # over the structure maps below -- computed once here (tagged,
        # see Element.__mul__) rather than re-derived on every call, and
        # used directly as self.e0/self.e1 everywhere internally too
        # (safe to tag: self.mul(...) always retags its own result with
        # self regardless of its arguments' tags, and tensor(...) always
        # builds a fresh untagged Element, so tagging e0/e1 can't leak an
        # incorrect tag into a H^{(x)n} result like Phi or comul(...)).
        one = self.unit()
        K2 = self._K(2)
        self.e0 = Fraction(1, 2) * (one + K2)
        self.e1 = Fraction(1, 2) * (one - K2)
        self.e0.alg = self
        self.e1.alg = self

    # -- scalars --------------------------------------------------------
    def i(self) -> CycloNum:
        """The imaginary unit, as an element of Q(zeta_8)."""
        return CycloNum.power(8, 2)

    def beta_scalar(self) -> CycloNum:
        """The algebra parameter beta = zeta_8**beta_power, as a scalar
        in Q(zeta_8). Deliberately *not* called ``beta()`` -- that name
        is taken by the QuasiHopfAlgebra interface method returning the
        coevaluation element Sbeta (a different thing entirely, matching
        the paper's own notation clash between the parameter "beta" and
        the element "Salpha/Sbeta")."""
        return CycloNum.power(8, self.beta_power)

    # -- basic data -----------------------------------------------------
    def basis(self):
        N = self.N
        return [(bits, k) for bits in _iproduct((0, 1), repeat=2 * N) for k in range(4)]

    def unit(self) -> Element:
        return Element.basis(((0,) * (2 * self.N), 0))

    def _K(self, exp: int = 1) -> Element:
        return Element.basis(((0,) * (2 * self.N), exp % 4))

    def _f(self, pos: int) -> Element:
        bits = [0] * (2 * self.N)
        bits[pos] = 1
        return Element.basis((tuple(bits), 0))

    @property
    def K(self) -> Element:
        """The generator K, tagged (see Element.__mul__) -- e.g.
        ``alg.K ** 4 == alg.unit()``."""
        e = self._K(1)
        e.alg = self
        return e

    def f(self, i: int, eps: str) -> Element:
        """The generator f_i^eps (eps = '+' or '-'), tagged -- e.g.
        ``alg.f(1, '+') * alg.f(1, '-')`` is ``alg.mul(...)``. i is
        1-indexed, matching the paper's f_i^+- notation (built on top of
        the position-indexed ``_f``, which stays as the untagged,
        0-indexed helper used internally by ``_comul_f``/``_antipode_f``)."""
        if eps not in ("+", "-"):
            raise ValueError("eps must be '+' or '-'")
        if not 1 <= i <= self.N:
            raise ValueError(f"i must be between 1 and N={self.N}")
        pos = 2 * (i - 1) + (0 if eps == "+" else 1)
        e = self._f(pos)
        e.alg = self
        return e

    # -- product ----------------------------------------------------------
    def multiply_basis(self, b1: BasisKey, b2: BasisKey) -> Element:
        key = (b1, b2)
        cached = self._mul_basis_cache.get(key)
        if cached is not None:
            return cached
        tokens = self._key_to_tokens(b1) + self._key_to_tokens(b2)
        result = self._reduce_word(tokens)
        self._mul_basis_cache[key] = result
        return result

    def _key_to_tokens(self, key: BasisKey):
        bits, k = key
        tokens = [("f", pos) for pos, b in enumerate(bits) if b]
        if k % 4 != 0:
            tokens.append(("K", k % 4))
        return tokens

    def _reduce_word(self, tokens) -> Element:
        """Reduce a list of ("f", pos) / ("K", exp) tokens to an Element
        in the normal-form basis (all f's present at most once, sorted
        by position, then K). This is *the* place the algebra's
        (anticommutator) relations live; every other structure map only
        ever calls self.mul, which bottoms out here -- same overall
        design as QuantumSl2Quasi._reduce_word, but the relations here
        are genuinely different: anticommutation (sign -1, not a
        q-power) between distinct generators, nilpotency
        ((f_i^eps)^2 = 0) instead of E^p = 0, and a *central-idempotent*
        correction term e1 (not a recursively-built commutator) when two
        conjugate generators f_i^+, f_i^- meet in the wrong order.
        """
        tokens = [t for t in tokens if not (t[0] == "K" and t[1] % 4 == 0)]

        for idx in range(len(tokens) - 1):
            t1, t2 = tokens[idx], tokens[idx + 1]

            if t1[0] == "K" and t2[0] == "K":
                # K^a K^b = K^(a+b mod 4)  (from K^4 = 1)
                merged = (t1[1] + t2[1]) % 4
                new_tokens = tokens[:idx] + ([("K", merged)] if merged else []) + tokens[idx + 2:]
                return self._reduce_word(new_tokens)

            if t1[0] == "K" and t2[0] == "f":
                # K^a f = (-1)^a f K^a  (from {f_i^+-, K} = 0)
                sign = -1 if t1[1] % 2 else 1
                new_tokens = tokens[:idx] + [t2, t1] + tokens[idx + 2:]
                result = self._reduce_word(new_tokens)
                return sign * result

            if t1[0] == "f" and t2[0] == "f":
                pos1, pos2 = t1[1], t2[1]
                if pos1 == pos2:
                    # (f_i^eps)^2 = 0  (from {f_i^eps, f_j^eps} = 0 at i=j)
                    return Element.zero()
                i1, i2 = pos1 // 2, pos2 // 2
                if i1 == i2:
                    # same i, opposite sign (pos1 != pos2 but same pair):
                    # correct order is '+' (even pos) before '-' (odd pos).
                    if pos1 < pos2:
                        continue  # already correct, keep scanning
                    # wrong order: f_i^- f_i^+ = e1 - f_i^+ f_i^-
                    # (from {f_i^+, f_j^-} = delta_ij * e1 at i=j)
                    prefix, suffix = tokens[:idx], tokens[idx + 2:]
                    correction = self._sandwich(prefix, self.e1, suffix)
                    swapped = prefix + [("f", pos2), ("f", pos1)] + suffix
                    return correction - self._reduce_word(swapped)
                if pos1 > pos2:
                    # different i, out of order: pure anticommutation, no
                    # correction term -- both {f_i^eps,f_j^eps} = 0 (same
                    # sign) and {f_i^+,f_j^-} = delta_ij*e1 (opposite sign)
                    # collapse to this once i != j, since delta_ij = 0 either way.
                    new_tokens = tokens[:idx] + [t2, t1] + tokens[idx + 2:]
                    return -1 * self._reduce_word(new_tokens)
                continue  # different i, already in order

        # No more inversions: tokens are already sorted f's (each once)
        # followed by at most one K token.
        bits = [0] * (2 * self.N)
        k = 0
        for t in tokens:
            if t[0] == "f":
                bits[t[1]] = 1
            else:
                k = t[1] % 4
        return Element.basis((tuple(bits), k))

    def _sandwich(self, prefix_tokens, middle: Element, suffix_tokens) -> Element:
        left = self._reduce_word(prefix_tokens) if prefix_tokens else self.unit()
        right = self._reduce_word(suffix_tokens) if suffix_tokens else self.unit()
        return self.mul(self.mul(left, middle), right)

    # -- coproduct --------------------------------------------------------
    def _omega(self, sign: int) -> Element:
        """omega_+- = (e0 +- i*e1) . K."""
        combo = self.e0 + (sign * self.i()) * self.e1
        return combo * self._K(1)

    def _comul_K1(self) -> Element:
        """Delta(K) = K (x) K - (1+(-1)^N) (e1.K) (x) (e1.K)."""
        e1K = self.e1 * self._K(1)
        K = self._K(1)
        correction = (1 + (-1) ** self.N) * tensor(e1K, e1K)
        return tensor(K, K) - correction

    def _comul_K_power(self, k: int) -> Element:
        cached = self._comul_K_power_cache.get(k)
        if cached is not None:
            return cached
        if k == 0:
            result = tensor(self.unit(), self.unit())
        else:
            result = self._comul_K_power(k - 1) * self._comul_K1()
        self._comul_K_power_cache[k] = result
        return result

    def _comul_f(self, pos: int) -> Element:
        """Delta(f_i^+-) = f_i^+- (x) 1 + omega_+- (x) f_i^+-, for the
        generator at bit position pos (+ if pos even, - if pos odd)."""
        cached = self._comul_f_cache.get(pos)
        if cached is not None:
            return cached
        sign = 1 if pos % 2 == 0 else -1
        f = self._f(pos)
        result = tensor(f, self.unit()) + tensor(self._omega(sign), f)
        self._comul_f_cache[pos] = result
        return result

    def comul(self, elem: Element) -> Element:
        result = Element()
        for (bits, k), coeff in elem.terms.items():
            result = result + coeff * self._comul_basis(bits, k)
        return result

    def _comul_basis(self, bits, k) -> Element:
        key = (bits, k)
        cached = self._comul_basis_cache.get(key)
        if cached is not None:
            return cached
        result = None
        for pos, b in enumerate(bits):
            if b:
                factor = self._comul_f(pos)
                result = factor if result is None else result * factor
        Kfactor = self._comul_K_power(k)
        result = Kfactor if result is None else result * Kfactor
        self._comul_basis_cache[key] = result
        return result

    # -- counit -------------------------------------------------------------
    def counit(self, elem: Element):
        total = CycloNum.zero(8)
        for (bits, k), coeff in elem.terms.items():
            if not any(bits):
                total = total + coeff
        return total

    # -- antipode -------------------------------------------------------------
    def _antipode_K1(self) -> Element:
        """S(K) = (e0 + (-1)^N e1) . K."""
        combo = self.e0 + Fraction((-1) ** self.N) * self.e1
        return combo * self._K(1)

    def _antipode_K_power(self, k: int) -> Element:
        cached = self._antipode_K_power_cache.get(k)
        if cached is not None:
            return cached
        result = self.unit() if k == 0 else self._antipode_K1() * self._antipode_K_power(k - 1)
        self._antipode_K_power_cache[k] = result
        return result

    def _antipode_f(self, pos: int) -> Element:
        """S(f_i^+-) = f_i^+- . (e0 +- (-1)^N i e1) . K."""
        cached = self._antipode_f_cache.get(pos)
        if cached is not None:
            return cached
        sign = 1 if pos % 2 == 0 else -1
        combo = self.e0 + (sign * ((-1) ** self.N) * self.i()) * self.e1
        result = self._f(pos) * combo * self._K(1)
        self._antipode_f_cache[pos] = result
        return result

    def antipode(self, elem: Element) -> Element:
        result = Element()
        for (bits, k), coeff in elem.terms.items():
            result = result + coeff * self._antipode_basis(bits, k)
        return result

    def _antipode_basis(self, bits, k) -> Element:
        """S(f_1^{e1}...f_last K^k) = S(K)^k . S(f_last) ... S(f_1)
        (S reverses order, same pattern as QuantumSl2Quasi._antipode_basis)."""
        key = (bits, k)
        cached = self._antipode_basis_cache.get(key)
        if cached is not None:
            return cached
        result = self._antipode_K_power(k)
        for pos in reversed(range(len(bits))):
            if bits[pos]:
                result = result * self._antipode_f(pos)
        self._antipode_basis_cache[key] = result
        return result

    def antipode_inv(self, elem: Element) -> Element:
        r"""S^-1, ported from arXiv:1812.10445 (stated right after
        eq (3.35), "for convenience"): S^-1(K) = K^{(-1)^N} -- the same
        formula as S(K) (see ``_antipode_K1()``), so S^-1(K^k) ==
        S(K^k), computed by ``_antipode_K_power`` below rather than
        duplicating it -- and S^-1(f_i^+-) = omega_+-.f_i^+- (contrast
        S(f_i^+-) = f_i^+-.(...).K -- the combo comes first, not last).
        Like S, an algebra anti-homomorphism (reverses word order), same
        pattern as ``antipode()``."""
        result = Element()
        for (bits, k), coeff in elem.terms.items():
            result = result + coeff * self._antipode_inv_basis(bits, k)
        return result

    def _antipode_inv_basis(self, bits, k) -> Element:
        key = (bits, k)
        cached = self._antipode_inv_basis_cache.get(key)
        if cached is not None:
            return cached
        result = self._antipode_K_power(k)  # S^-1(K) == S(K), see antipode_inv()
        for pos in reversed(range(len(bits))):
            if bits[pos]:
                result = result * self._antipode_inv_f(pos)
        self._antipode_inv_basis_cache[key] = result
        return result

    def _antipode_inv_f(self, pos: int) -> Element:
        """S^-1(f_i^+-) = omega_+- . f_i^+-."""
        cached = self._antipode_inv_f_cache.get(pos)
        if cached is not None:
            return cached
        sign = 1 if pos % 2 == 0 else -1
        result = self._omega(sign) * self._f(pos)
        self._antipode_inv_f_cache[pos] = result
        return result

    # -- associator and evaluation/coevaluation elements ------------------------
    def _assoc_third_factor(self, i_sign: int) -> Element:
        """(K^N - 1).e0 + (beta^2 (i_sign*i*K)^N - 1).e1, the third tensor
        leg of Phi (i_sign=+1) / Phi^-1 (i_sign=-1)."""
        one = self.unit()
        KN = self._K(self.N)
        term_a = (KN - one) * self.e0
        scalar = self.beta_scalar() ** 2 * (i_sign * self.i()) ** self.N
        bracket_b = scalar * KN - one
        term_b = bracket_b * self.e1
        return term_a + term_b

    def associator(self) -> Element:
        one = self.unit()
        term1 = tensor(tensor(one, one), one)
        term2 = tensor(tensor(self.e1, self.e1), self._assoc_third_factor(+1))
        return term1 + term2

    def associator_inv(self) -> Element:
        one = self.unit()
        term1 = tensor(tensor(one, one), one)
        term2 = tensor(tensor(self.e1, self.e1), self._assoc_third_factor(-1))
        return term1 + term2

    def alpha(self) -> Element:
        return self.unit()

    def beta(self) -> Element:
        """Sbeta = e0 + beta^2 (iK)^N e1."""
        scalar = self.beta_scalar() ** 2 * self.i() ** self.N
        return self.e0 + (scalar * self._K(self.N)) * self.e1

    # -- R-matrix, monodromy, Drinfeld and ribbon elements -----------------
    def _cartan_factor(self, n: int, m: int) -> Element:
        r"""rho_{n,m} = 1/2 sum_{a,b in {0,1}} (-1)^{ab} i^{-an+bm} K^a (x) K^b,
        for n, m in {0,1} (eq:car-fac in the paper)."""
        i = self.i()
        result = Element()
        for a in (0, 1):
            for b in (0, 1):
                sign = -1 if (a and b) else 1
                power = (-a * n + b * m) % 4
                coeff = Fraction(sign, 2) * (i**power)
                result = result + coeff * tensor(self._K(a), self._K(b))
        return result

    def _r_matrix_cartan_sum(self, beta_sign: int) -> Element:
        """sum_{n,m in {0,1}} beta^{beta_sign*n*m} * rho_{n,m} * e_n (x) e_m
        -- the first factor of R (beta_sign=+1). ``*`` here is the
        algebra product in H (x) H (both operands are arity-2 tensor
        elements -- e0/e1 are tagged, so `*` picks that up via its
        wildcard rule even though ``piece`` itself isn't; see
        ``Element.__mul__``)."""
        beta = self.beta_scalar()
        idem = (self.e0, self.e1)
        result = Element()
        for n in (0, 1):
            for m in (0, 1):
                scalar = beta ** (beta_sign * n * m)
                piece = scalar * self._cartan_factor(n, m)
                result = result + piece * tensor(idem[n], idem[m])
        return result

    def r_matrix(self) -> Element:
        r"""The universal R-matrix, an element of H (x) H:

            R = (sum_{n,m in {0,1}} beta^{nm} rho_{n,m} e_n (x) e_m) .
                prod_{k=1}^N (1(x)1 - 2 f_k^- omega_- (x) f_k^+)

        Ported from eq:R+Riv in the paper (Section 3.1). Entirely within
        Q(zeta_8) -- no field extension needed (contrast
        ``QuantumSl2Quasi.r_matrix()``), since both i and beta already
        live there.

        Written with tagged elements and ``*`` (never ``tensor_mul``/
        ``self.mul`` spelled out) for both the H-level product
        (``self.f(k, "-") * omega_minus``) and the H(x)H-level one
        (``product * local``, ``... * product``) -- ``*``'s arity-aware
        dispatch (see ``Element.__mul__``) already picks the right one;
        ``tensor(a, b)`` stays the one, explicit way to write an actual
        tensor product. ``self.f(k, "+")``/``self.f(k, "-")`` (already
        tagged) replace the equivalent, more roundabout
        ``self._f(2*(k-1))``/``self._f(2*(k-1)+1)``.
        """
        if self._r_matrix_cache is not None:
            return self._r_matrix_cache

        one = self.unit()
        omega_minus = self._omega(-1)
        product = tensor(one, one)
        for k in range(1, self.N + 1):
            local = tensor(one, one) - 2 * tensor(self.f(k, "-") * omega_minus, self.f(k, "+"))
            product = product * local

        result = self._r_matrix_cartan_sum(+1) * product
        self._r_matrix_cache = result
        return result

    def r_matrix_inv(self) -> Element:
        r"""The inverse of the universal R-matrix, an element of H (x) H:

            R^-1 = prod_{k=1}^N (1(x)1 + 2 f_k^- omega_- (x) f_k^+) .
                   (sum_{n,m in {0,1}} beta^{-nm} rho_{n,m} e_n (x) e_m)

        Ported from eq:R+Riv in the paper (Section 3.1) -- same
        construction as ``r_matrix()``, but with the product and Cartan
        sum in the opposite order, ``+2`` instead of ``-2`` in the local
        factor, and ``beta^{-nm}`` instead of ``beta^{nm}`` in the
        Cartan sum (``_r_matrix_cartan_sum(-1)``). Checked against
        ``r_matrix()`` by ``axioms.check_r_matrix_inverse``.
        """
        if self._r_matrix_inv_cache is not None:
            return self._r_matrix_inv_cache

        one = self.unit()
        omega_minus = self._omega(-1)
        product = tensor(one, one)
        for k in range(1, self.N + 1):
            local = tensor(one, one) + 2 * tensor(self.f(k, "-") * omega_minus, self.f(k, "+"))
            product = product * local

        result = product * self._r_matrix_cartan_sum(-1)
        self._r_matrix_inv_cache = result
        return result

    # monodromy()/drinfeld() are generic (see QuasiHopfAlgebra) -- not
    # overridden here.

    def ribbon(self) -> Element:
        r"""The ribbon element, an element of H:

            v = (e0 - beta*i*K*e1) . prod_{k=1}^N (1 - 2 f_k^+ f_k^-)

        Ported from eq:ribbon+ribinv in the paper (Section 3.1). Written
        with tagged elements and ``*`` (see ``r_matrix()``'s docstring
        for why -- same idea, ``*`` for every algebra product, no
        ``tensor()``/tensor product needed here since this is a
        single-leg element; also uses ``self.f(k, "+")``/``self.f(k, "-")``
        instead of the more roundabout ``self._f(2*(k-1))``/
        ``self._f(2*(k-1)+1)``).
        """
        if self._ribbon_cache is not None:
            return self._ribbon_cache

        beta = self.beta_scalar()
        K_e1 = self._K(1) * self.e1
        prefactor = self.e0 - (beta * self.i()) * K_e1

        product = self.unit()
        for k in range(1, self.N + 1):
            local = self.unit() - 2 * (self.f(k, "+") * self.f(k, "-"))
            product = product * local

        result = prefactor * product
        self._ribbon_cache = result
        return result

    def ribbon_inv(self) -> Element:
        r"""The inverse of the ribbon element, an element of H:

            v^-1 = (e0 - beta^-1*i*K*e1) . prod_{k=1}^N (1 + 2 f_k^+ f_k^- K^2)

        Ported from eq:ribbon+ribinv in the paper (Section 3.1) -- same
        construction as ``ribbon()``, but with ``beta^-1`` instead of
        ``beta`` and an extra ``K^2`` factor in the product. Checked
        against ``ribbon()`` by ``axioms.check_ribbon_inverse``.
        """
        if self._ribbon_inv_cache is not None:
            return self._ribbon_inv_cache

        beta = self.beta_scalar()
        K_e1 = self._K(1) * self.e1
        prefactor = self.e0 - (beta ** (-1) * self.i()) * K_e1

        product = self.unit()
        for k in range(1, self.N + 1):
            local = self.unit() + 2 * (self.f(k, "+") * self.f(k, "-") * self.K**2)
            product = product * local

        result = prefactor * product
        self._ribbon_inv_cache = result
        return result

    def left_integral(self) -> Element:
        r"""A two-sided integral, an element of H:

            Lambda = 2^N beta^2 f_1^+ f_1^- ... f_N^+ f_N^- . e0 . (1+K)

        Ported from eq:int-Q in the paper (Section 3.5), which gives
        this formula for any scalar nu (the space of two-sided
        integrals is one-dimensional, so nu is a free normalisation) --
        nu=1 is fixed here. The paper verifies directly that
        Lambda.K == Lambda == K.Lambda and Lambda.f_i^+- == 0 ==
        f_i^+-.Lambda, from which Lambda.h == eps(h).Lambda == h.Lambda
        follows for every h in H (eps(K)=1, eps(f_i^+-)=0). Genuinely
        two-sided, so ``right_integral()`` below just returns this same
        element. Checked by ``axioms.check_left_integral``/
        ``axioms.check_right_integral``.
        """
        if self._left_integral_cache is not None:
            return self._left_integral_cache

        product = self.unit()
        for k in range(1, self.N + 1):
            product = product * self.f(k, "+") * self.f(k, "-")

        scalar = (2**self.N) * self.beta_scalar() ** 2
        result = (scalar * product) * self.e0 * (self.unit() + self.K)
        self._left_integral_cache = result
        return result

    def right_integral(self) -> Element:
        """Q's integral is two-sided (see ``left_integral()``'s
        docstring), so this is the same element."""
        return self.left_integral()

    # f_element()/f_element_inv() are both generic (see QuasiHopfAlgebra)
    # -- not overridden here. f_element_inv() was originally hand-derived
    # for Q before the generic Drinfeld-eq-(1.36) version existed (an
    # elementary block-by-block inversion of eq:def:F-Q -- H (x) H is the
    # tensor-product *algebra*, e0 (x) e0/e0 (x) e1/e1 (x) e0/e1 (x) e1
    # are orthogonal idempotents F splits into); confirmed to agree with
    # the generic version exactly and kept as a regression test instead
    # of an override, see tests/_special_elements.py's
    # symplectic_fermion_expected_f_element_inv and
    # tests/test_symplectic_fermion.py's
    # test_f_element_inv_matches_explicit_formula.

    def modulus(self, elem: Element):
        """Q is unimodular (eq:int-Q's remark, Section 3.5: "In
        particular, Q is unimodular"), so the modulus is just the
        counit."""
        return self.counit(elem)

    def left_cointegral(self, elem: Element):
        r"""A left (and, since Q's pivot has order 2, also right --
        ``right_cointegral()`` below returns the same functional)
        cointegral, ported from arXiv:1812.10445 eq (5.24)-(5.25):
        nonzero only on the top-degree basis element
        f_1^+f_1^-...f_N^+f_N^- . K^i, where it takes the value
        a_+, b_+, a_-, b_- for i=0,1,2,3 respectively, with
        a_+- = beta^2 +- [N even], b_+- = +-i [N odd].

        The paper states this for its *own* basis convention
        (f_1^+...f_N^+ . f_1^-...f_N^- . K^i, all +'s before all -'s),
        which differs from this module's normal-form ordering
        (f_1^+f_1^-f_2^+f_2^-..., interleaved -- see the module
        docstring's basis description) by the sign of the permutation
        reordering N pairs of anticommuting generators into interleaved
        order, (-1)^(N(N-1)/2) -- confirmed empirically here (not just
        derived by hand) via ``axioms.check_left_cointegral``, which
        fails immediately if this sign is wrong.
        """
        top = (1,) * (2 * self.N)
        sign = -1 if (self.N * (self.N - 1) // 2) % 2 else 1
        beta2 = self.beta_scalar() ** 2
        if self.N % 2 == 0:
            values = {0: beta2 + 1, 1: CycloNum.zero(8), 2: beta2 - 1, 3: CycloNum.zero(8)}
        else:
            values = {0: beta2, 1: self.i(), 2: beta2, 3: -self.i()}
        total = CycloNum.zero(8)
        for (bits, k), coeff in elem.terms.items():
            if bits == top:
                total = total + sign * coeff * values[k]
        return total

    def right_cointegral(self, elem: Element):
        """Q's cointegral is two-sided, see ``left_cointegral()``."""
        return self.left_cointegral(elem)

    # -- readable output ---------------------------------------------------
    def pretty(self, elem: Element) -> str:
        """Human-readable string, e.g. ``"2*f₁⁺ f₁⁻ + (1-i)*K""``."""
        if not elem.terms:
            return "0"
        rendered = []
        for key, coeff in sorted(elem.terms.items(), key=lambda kv: kv[0]):
            coeff_str = self._format_coeff(coeff)
            if coeff_str == "0":
                continue
            key_str = self._format_key(key)
            if key_str == "1":
                rendered.append(coeff_str)
            elif coeff_str == "1":
                rendered.append(key_str)
            elif coeff_str == "-1":
                rendered.append(f"-{key_str}")
            elif " + " in coeff_str or " - " in coeff_str:
                rendered.append(f"({coeff_str})*{key_str}")
            else:
                rendered.append(f"{coeff_str}*{key_str}")
        if not rendered:
            return "0"
        out = rendered[0]
        for term in rendered[1:]:
            out += f" - {term[1:]}" if term.startswith("-") else f" + {term}"
        return out

    def _format_key(self, key) -> str:
        if isinstance(key, TensorKey):
            return f" {TENSOR} ".join(self._format_key(k) for k in key)
        bits, k = key
        parts = []
        for pos, b in enumerate(bits):
            if b:
                idx = pos // 2 + 1
                sign = "+" if pos % 2 == 0 else "-"
                parts.append(f"f{subscript(idx)}{superscript(sign)}")
        if k == 1:
            parts.append("K")
        elif k > 1:
            parts.append(f"K{superscript(k)}")
        return " ".join(parts) if parts else "1"

    def _format_coeff(self, c) -> str:
        if isinstance(c, CycloNum):
            return self._format_cyclonum(c)
        return str(c)

    def _format_cyclonum(self, c: CycloNum) -> str:
        if c.n is None:
            return str(c.poly.coeffs[0])

        zeta8 = f"ζ{subscript(8)}"  # zeta_8

        def power(k):
            if k == 0:
                return ""
            if k == 1:
                return zeta8
            if k == 2:
                return "i"
            return f"{zeta8}{superscript(k)}"

        terms = []
        for k, coeff in enumerate(c.poly.coeffs):
            if coeff == 0:
                continue
            p_str = power(k)
            if p_str == "":
                terms.append(f"{coeff}")
            elif coeff == 1:
                terms.append(p_str)
            elif coeff == -1:
                terms.append(f"-{p_str}")
            else:
                terms.append(f"{coeff}*{p_str}")
        if not terms:
            return "0"
        out = terms[0]
        for t in terms[1:]:
            out += f" - {t[1:]}" if t.startswith("-") else f" + {t}"
        return out
