"""Two dependency-free coefficient rings, for the two situations that
come up across this package's examples: q as a completely free formal
parameter, or q specialised to an actual root of unity.

- ``QRational`` / ``LaurentPoly``: Q(q), the field of rational functions
  in one *free* variable q -- use this whenever an algebra's relations
  make sense for generic q (this is the common case, e.g. most quantum
  groups before any restriction/truncation is imposed).

- ``CycloNum`` / ``Poly``: Q(zeta_n) = Q[x]/(Phi_n(x)), the field
  generated by adjoining an actual primitive n'th root of unity -- use
  this when an algebra's relations only make sense for such a q. This
  is not just a convenience: it can be a mathematical necessity. For
  example, the ``quantum_sl2_quasi`` example imposes both
  ``K^{2p} = 1`` (a relation on the generator K) and
  ``K E K^-1 = q^2 E``; conjugating the latter around the cycle 2p
  times gives ``K^{2p} E K^{-2p} = q^{4p} E``, and since the left side
  must equal E (because K^{2p} = 1), consistency *forces*
  ``q^{4p} = 1`` -- so q cannot be a free variable there. The original
  Mathematica source (reference/hopf-Uqsl2-quasi.txt) handles this by
  specialising q to e^{i pi / p}, a primitive 2p'th root of unity, and
  its ``qqreduce`` routine is precisely a hand-rolled version of what
  ``CycloNum`` does directly: reduction modulo the minimal (cyclotomic)
  polynomial of that root. Note that Q[x]/(x^n - 1) itself would *not*
  be enough (it has zero divisors -- e.g. q - q^-1 vanishes at q = 1 or
  q = -1, both roots of x^n - 1 -- so it is not a field and formulas
  like 1/(q - q^-1), needed for the quantum-group commutator [E, F],
  would not make sense); Q(zeta_n) fixes this by quotienting by the
  *irreducible* cyclotomic polynomial instead.

Which one a given algebra should use is a mathematical property of its
relations, not a framework choice -- see the "generic vs root of unity"
note in CLAUDE.md for how to tell which applies to a new example. Both
rings expose the same duck-typed surface (``+``, ``-``, ``*``, ``/``,
``**``, ``is_zero()``, and free mixing with plain ``int``/``Fraction``
constants), and :class:`~hopfsym.element.Element` never hard-codes
either one -- an Element's coefficients can be QRational, CycloNum, or
in principle any other ring implementing the same operations.

Everything here is plain, dependency-free Python: no simplify() black
box anywhere, just exact polynomial/rational-function arithmetic (plus,
for CycloNum, the extended Euclidean algorithm to compute inverses).
"""

from __future__ import annotations

from fractions import Fraction
from functools import lru_cache
from typing import List, Union

Number = Union[int, Fraction]


# ---------------------------------------------------------------------------
# Plain rational polynomials, used only to build cyclotomic polynomials and
# to do the field arithmetic below.
# ---------------------------------------------------------------------------


class Poly:
    """A polynomial with rational coefficients; ``coeffs[i]`` is the
    coefficient of ``x**i``. Always kept trimmed (no trailing zeros,
    except the zero polynomial itself, represented as ``[0]``)."""

    __slots__ = ("coeffs",)

    def __init__(self, coeffs: List[Number]):
        # Fraction(x) is surprisingly costly to call on something that's
        # already a Fraction (this constructor is extremely hot), so
        # skip it when we can.
        coeffs = [c if type(c) is Fraction else Fraction(c) for c in coeffs] if coeffs else [
            Fraction(0)
        ]
        while len(coeffs) > 1 and coeffs[-1] == 0:
            coeffs.pop()
        self.coeffs = coeffs

    @classmethod
    def zero(cls) -> "Poly":
        return cls([0])

    @classmethod
    def one(cls) -> "Poly":
        return cls([1])

    @classmethod
    def monomial(cls, degree: int, coeff: Number = 1) -> "Poly":
        return cls([0] * degree + [coeff])

    def degree(self) -> int:
        return -1 if self.is_zero() else len(self.coeffs) - 1

    def is_zero(self) -> bool:
        return len(self.coeffs) == 1 and self.coeffs[0] == 0

    def scaled(self, c: Number) -> "Poly":
        c = Fraction(c)
        return Poly([x * c for x in self.coeffs])

    def __add__(self, other: "Poly") -> "Poly":
        n = max(len(self.coeffs), len(other.coeffs))
        a = self.coeffs + [Fraction(0)] * (n - len(self.coeffs))
        b = other.coeffs + [Fraction(0)] * (n - len(other.coeffs))
        return Poly([x + y for x, y in zip(a, b)])

    def __neg__(self) -> "Poly":
        return Poly([-c for c in self.coeffs])

    def __sub__(self, other: "Poly") -> "Poly":
        return self + (-other)

    def __mul__(self, other: "Poly") -> "Poly":
        result = [Fraction(0)] * (len(self.coeffs) + len(other.coeffs) - 1)
        for i, a in enumerate(self.coeffs):
            if a == 0:
                continue
            for j, b in enumerate(other.coeffs):
                result[i + j] += a * b
        return Poly(result)

    def divmod(self, other: "Poly"):
        """Polynomial long division: returns (quotient, remainder) with
        ``self == quotient * other + remainder`` and
        ``remainder.degree() < other.degree()``."""
        if other.is_zero():
            raise ZeroDivisionError("polynomial division by zero")
        rem = Poly(list(self.coeffs))
        quot = [Fraction(0)] * max(1, self.degree() - other.degree() + 1)
        lead_o = other.coeffs[-1]
        while not rem.is_zero() and rem.degree() >= other.degree():
            shift = rem.degree() - other.degree()
            coeff = rem.coeffs[-1] / lead_o
            quot[shift] = coeff
            rem = rem - Poly([0] * shift + other.scaled(coeff).coeffs)
        return Poly(quot), rem

    def __eq__(self, other):
        if not isinstance(other, Poly):
            return NotImplemented
        return (self - other).is_zero()

    def __repr__(self):
        terms = []
        for i, c in enumerate(self.coeffs):
            if c == 0:
                continue
            terms.append(f"{c}*x^{i}" if i > 0 else f"{c}")
        return " + ".join(terms) if terms else "0"


def _divisors(n: int) -> List[int]:
    return [d for d in range(1, n + 1) if n % d == 0]


@lru_cache(maxsize=None)
def cyclotomic_polynomial(n: int) -> Poly:
    """The n'th cyclotomic polynomial Phi_n(x), via the standard
    recursive formula ``Phi_n(x) = (x^n - 1) / prod_{d | n, d < n} Phi_d(x)``."""
    if n == 1:
        return Poly([-1, 1])  # x - 1
    prod = Poly.one()
    for d in _divisors(n):
        if d < n:
            prod = prod * cyclotomic_polynomial(d)
    xn_minus_1 = Poly.monomial(n, 1) - Poly.one()
    quot, rem = xn_minus_1.divmod(prod)
    assert rem.is_zero(), "n | should always divide evenly; this is a bug if it doesn't"
    return quot


def _poly_egcd(a: Poly, b: Poly):
    """Extended Euclidean algorithm: returns (g, u, v) with
    ``u*a + v*b == g`` and g a gcd of a and b (up to a scalar)."""
    old_r, r = a, b
    old_s, s = Poly.one(), Poly.zero()
    old_t, t = Poly.zero(), Poly.one()
    while not r.is_zero():
        q, _ = old_r.divmod(r)
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    return old_r, old_s, old_t


# ---------------------------------------------------------------------------
# The field Q(zeta_n) itself.
# ---------------------------------------------------------------------------


class CycloNum:
    """An element of Q(zeta_n) = Q[x]/(Phi_n(x)).

    ``n`` is the field's degree parameter (x represents a primitive
    n'th root of unity); ``n=None`` marks a plain rational constant,
    which is valid in *any* such field and is automatically promoted to
    match whatever concrete n it is combined with (this is what lets
    you write e.g. ``Fraction(1, 2) * some_element`` without having to
    know n up front).
    """

    __slots__ = ("n", "poly")

    def __init__(self, n, poly: Poly):
        self.n = n
        self.poly = poly if n is None else _reduce_mod_phi(n, poly)

    @classmethod
    def zero(cls, n=None) -> "CycloNum":
        return cls(n, Poly.zero())

    @classmethod
    def one(cls, n=None) -> "CycloNum":
        return cls(n, Poly.one())

    @classmethod
    def constant(cls, c: Number) -> "CycloNum":
        return cls(None, Poly([c]))

    @classmethod
    def power(cls, n: int, k: int) -> "CycloNum":
        """zeta_n ** k, for any integer k (positive, zero or negative)."""
        return cls(n, Poly.monomial(k % n, 1))

    @staticmethod
    def _as_cn(x) -> "CycloNum":
        if isinstance(x, CycloNum):
            return x
        if isinstance(x, (int, Fraction)):
            return CycloNum.constant(x)
        return NotImplemented

    def _combine_n(self, other: "CycloNum"):
        if self.n is None:
            return other.n
        if other.n is None or other.n == self.n:
            return self.n
        raise ValueError(f"mismatched cyclotomic field degree: {self.n} vs {other.n}")

    def __add__(self, other):
        other = CycloNum._as_cn(other)
        if other is NotImplemented:
            return NotImplemented
        return CycloNum(self._combine_n(other), self.poly + other.poly)

    __radd__ = __add__

    def __neg__(self):
        return CycloNum(self.n, -self.poly)

    def __sub__(self, other):
        other = CycloNum._as_cn(other)
        if other is NotImplemented:
            return NotImplemented
        return self + (-other)

    def __rsub__(self, other):
        return (-self) + other

    def __mul__(self, other):
        other = CycloNum._as_cn(other)
        if other is NotImplemented:
            return NotImplemented
        return CycloNum(self._combine_n(other), self.poly * other.poly)

    __rmul__ = __mul__

    def inverse(self) -> "CycloNum":
        if self.is_zero():
            raise ZeroDivisionError("division by zero in a cyclotomic field")
        if self.n is None:
            # A nonzero rational constant: invert the single coefficient.
            return CycloNum.constant(1 / self.poly.coeffs[0])
        phi = cyclotomic_polynomial(self.n)
        g, u, _ = _poly_egcd(self.poly, phi)
        # Phi_n is irreducible over Q and self.poly is nonzero mod Phi_n,
        # so g is a nonzero constant.
        c = g.coeffs[0]
        return CycloNum(self.n, u.scaled(1 / c))

    def __truediv__(self, other):
        other = CycloNum._as_cn(other)
        if other is NotImplemented:
            return NotImplemented
        n = self._combine_n(other)
        return CycloNum(n, self.poly) * CycloNum(n, other.poly).inverse()

    def __rtruediv__(self, other):
        other = CycloNum._as_cn(other)
        if other is NotImplemented:
            return NotImplemented
        return other / self

    def __pow__(self, k: int) -> "CycloNum":
        if k < 0:
            return self.inverse() ** (-k)
        result = CycloNum.one(self.n)
        base = self
        while k > 0:
            if k & 1:
                result = result * base
            base = base * base
            k >>= 1
        return result

    def is_zero(self) -> bool:
        return self.poly.is_zero()

    def __eq__(self, other):
        other = CycloNum._as_cn(other)
        if other is NotImplemented:
            return NotImplemented
        self._combine_n(other)
        return (self - other).is_zero()

    def __hash__(self):
        raise TypeError("CycloNum is not hashable (used only as a coefficient)")

    def __repr__(self):
        tag = "Q" if self.n is None else f"Q(zeta_{self.n})"
        return f"[{self.poly!r}]_{tag}"


def _reduce_mod_phi(n: int, poly: Poly) -> Poly:
    _, rem = poly.divmod(cyclotomic_polynomial(n))
    return rem


CYCLO_ZERO = CycloNum.zero()
CYCLO_ONE = CycloNum.one()


# ---------------------------------------------------------------------------
# Q(q): rational functions in one *free* variable, for algebras whose
# relations hold for generic q (no root-of-unity specialisation needed).
# ---------------------------------------------------------------------------


class LaurentPoly:
    """An element of Q[q, q^-1]: ``sum_k coeffs[k] * q**k``, k ranging
    over the integers (positive, zero, or negative)."""

    __slots__ = ("coeffs",)

    def __init__(self, coeffs: dict = None):
        self.coeffs: dict = {}
        if coeffs:
            for k, v in coeffs.items():
                self._set(k, v)

    def _set(self, k: int, v: Number) -> None:
        v = Fraction(v)
        if v == 0:
            self.coeffs.pop(k, None)
        else:
            self.coeffs[k] = v

    @classmethod
    def zero(cls) -> "LaurentPoly":
        return cls()

    @classmethod
    def one(cls) -> "LaurentPoly":
        return cls({0: 1})

    @classmethod
    def constant(cls, c: Number) -> "LaurentPoly":
        return cls({0: c})

    @classmethod
    def monomial(cls, power: int, coeff: Number = 1) -> "LaurentPoly":
        return cls({power: coeff})

    @staticmethod
    def _as_poly(x):
        if isinstance(x, LaurentPoly):
            return x
        if isinstance(x, (int, Fraction)):
            return LaurentPoly.constant(x)
        return NotImplemented

    def __add__(self, other):
        other = LaurentPoly._as_poly(other)
        if other is NotImplemented:
            return NotImplemented
        result = LaurentPoly(dict(self.coeffs))
        for k, v in other.coeffs.items():
            result._set(k, result.coeffs.get(k, 0) + v)
        return result

    __radd__ = __add__

    def __neg__(self):
        return LaurentPoly({k: -v for k, v in self.coeffs.items()})

    def __sub__(self, other):
        other = LaurentPoly._as_poly(other)
        if other is NotImplemented:
            return NotImplemented
        return self + (-other)

    def __rsub__(self, other):
        return (-self) + other

    def __mul__(self, other):
        other = LaurentPoly._as_poly(other)
        if other is NotImplemented:
            return NotImplemented
        result = LaurentPoly()
        for k1, v1 in self.coeffs.items():
            for k2, v2 in other.coeffs.items():
                k3 = k1 + k2
                result._set(k3, result.coeffs.get(k3, 0) + v1 * v2)
        return result

    __rmul__ = __mul__

    def is_zero(self) -> bool:
        return len(self.coeffs) == 0

    def __eq__(self, other):
        other = LaurentPoly._as_poly(other)
        if other is NotImplemented:
            return NotImplemented
        return (self - other).is_zero()

    def __hash__(self):
        return hash(frozenset(self.coeffs.items()))

    def __repr__(self):
        if not self.coeffs:
            return "0"
        parts = []
        for k in sorted(self.coeffs):
            v = self.coeffs[k]
            if k == 0:
                parts.append(f"{v}")
            elif v == 1:
                parts.append(f"q^{k}")
            elif v == -1:
                parts.append(f"-q^{k}")
            else:
                parts.append(f"{v}*q^{k}")
        return " + ".join(parts).replace("+ -", "- ")


class QRational:
    """An element of Q(q): a numerator/denominator pair of LaurentPoly.

    Fractions are kept unreduced; equality and zero-testing are exact
    (via cross-multiplication over the common denominator), which is
    all correctness ever requires here.
    """

    __slots__ = ("num", "den")

    def __init__(self, num, den=None):
        num = num if isinstance(num, LaurentPoly) else LaurentPoly.constant(num)
        den = LaurentPoly.one() if den is None else (
            den if isinstance(den, LaurentPoly) else LaurentPoly.constant(den)
        )
        if den.is_zero():
            raise ZeroDivisionError("QRational with zero denominator")
        self.num = num
        self.den = den

    @classmethod
    def zero(cls) -> "QRational":
        return cls(LaurentPoly.zero())

    @classmethod
    def one(cls) -> "QRational":
        return cls(LaurentPoly.one())

    @classmethod
    def constant(cls, c: Number) -> "QRational":
        return cls(LaurentPoly.constant(c))

    @classmethod
    def q_power(cls, exp: int) -> "QRational":
        """q**exp, for any integer exp (positive, zero, or negative)."""
        if exp >= 0:
            return cls(LaurentPoly.monomial(exp, 1))
        return cls(LaurentPoly.one(), LaurentPoly.monomial(-exp, 1))

    @staticmethod
    def _as_qr(x) -> "QRational":
        if isinstance(x, QRational):
            return x
        if isinstance(x, (LaurentPoly, int, Fraction)):
            return QRational(x)
        return NotImplemented

    def __add__(self, other):
        other = QRational._as_qr(other)
        if other is NotImplemented:
            return NotImplemented
        return QRational(self.num * other.den + other.num * self.den, self.den * other.den)

    __radd__ = __add__

    def __neg__(self):
        return QRational(-self.num, self.den)

    def __sub__(self, other):
        other = QRational._as_qr(other)
        if other is NotImplemented:
            return NotImplemented
        return self + (-other)

    def __rsub__(self, other):
        return (-self) + other

    def __mul__(self, other):
        other = QRational._as_qr(other)
        if other is NotImplemented:
            return NotImplemented
        return QRational(self.num * other.num, self.den * other.den)

    __rmul__ = __mul__

    def __truediv__(self, other):
        other = QRational._as_qr(other)
        if other is NotImplemented:
            return NotImplemented
        return QRational(self.num * other.den, self.den * other.num)

    def __rtruediv__(self, other):
        other = QRational._as_qr(other)
        if other is NotImplemented:
            return NotImplemented
        return other / self

    def __pow__(self, n: int) -> "QRational":
        if n >= 0:
            return QRational(self.num_pow(n), self.den_pow(n))
        inv = QRational(self.den, self.num)
        return inv.__pow__(-n)

    def num_pow(self, n):
        result = LaurentPoly.one()
        for _ in range(n):
            result = result * self.num
        return result

    def den_pow(self, n):
        result = LaurentPoly.one()
        for _ in range(n):
            result = result * self.den
        return result

    def is_zero(self) -> bool:
        return self.num.is_zero()

    def __eq__(self, other):
        other = QRational._as_qr(other)
        if other is NotImplemented:
            return NotImplemented
        return (self - other).is_zero()

    def __hash__(self):
        raise TypeError("QRational is not hashable (used only as a coefficient)")

    def __repr__(self):
        if self.den == LaurentPoly.one():
            return repr(self.num)
        return f"({self.num!r})/({self.den!r})"


def q_power(exp: int) -> QRational:
    """q**exp in Q(q) (free variable), for any integer exp."""
    return QRational.q_power(exp)


QRAT_ZERO = QRational.zero()
QRAT_ONE = QRational.one()
